---@meta

---
---HOUSE_STATUS represents data related to a house in the game, including requirements, icon, generated resources, density data, name, and description.
---Cloneable
---[Reference](https://www.polymorph.games/foundation/modding/api/house_status)
---
---@class HOUSE_STATUS
---@field DataType 'HOUSE_STATUS' The name of this data type (always "HOUSE_STATUS")
---@field AssetHouseRequirementList? list<HOUSE_REQUIREMENT> list of asset IDs representing the house requirements
---@field HouseIcon? ATLAS_CELL asset ID representing the house icon, default is nil
---@field ResourceGenerated? RESOURCE asset ID representing the resource generated by the house
---@field DataHouseDensityList? list<DATA_HOUSE_DENSITY> list of DATA_HOUSE_DENSITY values for the house density data
---@field Name? string string value representing the name of the house
---@field Description? string string value representing the description of the house

local HOUSE_STATUS = {}

HOUSE_STATUS.DataType = "HOUSE_STATUS"

---Class methods and properties go here

return HOUSE_STATUS