---@meta

---
---Dynamic enumeration representing categories for beautification objects.
---Used to specify the type of beautification in the game modding API.
---[Reference](https://www.polymorph.games/foundation/modding/api/beautification_category)
---
---@enum BEAUTIFICATION_CATEGORY
BEAUTIFICATION_CATEGORY = {
    GENERAL = "GENERAL",
    BUSH = "BUSH",
    TREE = "TREE",
    FOUNTAIN = "FOUNTAIN",
    BENCH = "BENCH",
    SCULPTURE = "SCULPTURE",
    MASTERPIECE_CROSS = "MASTERPIECE_CROSS",
    MASTERPIECE_SHRINE = "MASTERPIECE_SHRINE",
    MASTERPIECE_STAINEDGLASS = "MASTERPIECE_STAINEDGLASS",
    MASTERPIECE_GATE = "MASTERPIECE_GATE",
    MASTERPIECE_LUSH_GARDEN = "MASTERPIECE_LUSH_GARDEN",
    MASTERPIECE_AUTOMATE_FOUNTAIN = "MASTERPIECE_AUTOMATE_FOUNTAIN",
    MASTERPIECE_KNIGHT_STATUE = "MASTERPIECE_KNIGHT_STATUE",
    MASTERPIECE_OFFICINAL_GARDEN = "MASTERPIECE_OFFICINAL_GARDEN",
    MASTERPIECE_FOUNTAIN = "MASTERPIECE_FOUNTAIN",
    MASTERPIECE_CROSS_CORE = "MASTERPIECE_CROSS_CORE",
    MASTERPIECE_SHRINE_CORE = "MASTERPIECE_SHRINE_CORE",
}