---@meta

---
---BUILDING_STATUS enum represents various states and conditions of buildings or building parts in the game.
---
---[Reference](https://www.polymorph.games/foundation/modding/api/building_status)
---
---@enum BUILDING_STATUS
BUILDING_STATUS = {
    NONE = "NONE",
    BUILDING_MISSING_REQUIREMENTS = "BUILDING_MISSING_REQUIREMENTS",
    PART_BEING_PLACED = "PART_BEING_PLACED",
    READY_TO_BUILD = "READY_TO_BUILD",
    PART_UNDER_CONSTRUCTION = "PART_UNDER_CONSTRUCTION",
    PART_NORMAL = "PART_NORMAL",
    PART_DECAYING = "PART_DECAYING",
    PART_IN_RUINS = "PART_IN_RUINS",
    WORKPLACE_WORKING = "WORKPLACE_WORKING",
    WORKPLACE_LACK_RESOURCE = "WORKPLACE_LACK_RESOURCE",
    WORKPLACE_LACK_WORKER = "WORKPLACE_LACK_WORKER",
    WORKPLACE_NO_STORAGE = "WORKPLACE_NO_STORAGE",
    WORKPLACE_STORAGE_FULL = "WORKPLACE_STORAGE_FULL",
    WORKPLACE_PAUSED = "WORKPLACE_PAUSED",
    CONSTRUCTIONSITE_LACK_RESOURCE = "CONSTRUCTIONSITE_LACK_RESOURCE",
    ZONE_MISSING = "ZONE_MISSING",
    ZONE_TOO_SMALL = "ZONE_TOO_SMALL",
    ZONE_EMPTY = "ZONE_EMPTY",
    ZONE_FULL = "ZONE_FULL",
    WORKPLACE_NO_TREE_TYPE = "WORKPLACE_NO_TREE_TYPE",
    MISSING_HOUSING_REQUIREMENT = "MISSING_HOUSING_REQUIREMENT",
    UNREACHABLE_PREVIEW = "UNREACHABLE_PREVIEW",
    UNREACHABLE = "UNREACHABLE",
}