---@meta

---
---Category: Asset
---
---@class DESIRABILITY_HOUSE_SELECTION_FACTOR:HOUSE_SELECTION_FACTOR
---@field DataType 'DESIRABILITY_HOUSE_SELECTION_FACTOR' The name of this data type (always "DESIRABILITY_HOUSE_SELECTION_FACTOR")

local DESIRABILITY_HOUSE_SELECTION_FACTOR = {}

DESIRABILITY_HOUSE_SELECTION_FACTOR.DataType = "DESIRABILITY_HOUSE_SELECTION_FACTOR"

---Class methods and properties go here

return DESIRABILITY_HOUSE_SELECTION_FACTOR