---@meta

---@class INTERACTIVE_LOCATION_SETUP : ASSET
---@field PurposeList list<INTERACTIVE_LOCATION_PURPOSE> # List of enum values.
---@field CharacterSetup? CHARACTER_SETUP # Optional CHARACTER_SETUP value. Default: nil.

local INTERACTIVE_LOCATION_SETUP = {}

---@type INTERACTIVE_LOCATION_SETUP
_G.INTERACTIVE_LOCATION_SETUP = INTERACTIVE_LOCATION_SETUP
