---@meta

---@class PREFABS
---@field PREFAB_BODY_FEMALE_DEFAULT string @readonly
---@field PREFAB_BODY_MALE_DEFAULT string @readonly
---@field PREFAB_GAME_CAMERA string @readonly
---@field PREFAB_LIVESTOCK_COW string @readonly
---@field PREFAB_MANAGER string @readonly
---@field PREFAB_MINERAL_SOURCE_1 string @readonly
---@field PREFAB_MINERAL_SOURCE_2 string @readonly
---@field PREFAB_MINERAL_SOURCE_3 string @readonly
---@field PREFAB_RESOURCE_BERRIES string @readonly
---@field PREFAB_RESOURCE_FISH string @readonly
---@field PREFAB_RESOURCE_IRON_01 string @readonly
---@field PREFAB_RESOURCE_IRON_02 string @readonly
---@field PREFAB_RESOURCE_IRON_03 string @readonly
---@field PREFAB_RESOURCE_ROCK_01 string @readonly
---@field PREFAB_RESOURCE_ROCK_02 string @readonly
---@field PREFAB_RESOURCE_ROCK_03 string @readonly
---@field PREFAB_RESOURCE_ROCK_04 string @readonly
---@field PREFAB_RESOURCE_VISUAL_COAL_CRATE string @readonly
---@field PREFAB_RESOURCE_VISUAL_CRATE string @readonly
---@field PREFAB_TOOL_BARTENDER_WINE_BOTTLE string @readonly
---@field PREFAB_TOOL_BEEKEEPER_SMOKER string @readonly
---@field PREFAB_TOOL_BLACKSMITH_GRIP string @readonly
---@field PREFAB_TOOL_BLACKSMITH_HAMMER string @readonly
---@field PREFAB_TOOL_BUTCHER_KNIFE string @readonly
---@field PREFAB_TOOL_CHEESE_MAKER_SPOON string @readonly
---@field PREFAB_TOOL_COOK_KNIFE string @readonly
---@field PREFAB_TOOL_COOPER_PLANE string @readonly
---@field PREFAB_TOOL_ENVOY_SCROLL string @readonly
---@field PREFAB_TOOL_ENVOY_SCROLL_LONG string @readonly
---@field PREFAB_TOOL_FARMER_SEED_BAG string @readonly
---@field PREFAB_TOOL_FISHERMAN_ROD string @readonly
---@field PREFAB_TOOL_GLASS_SMELTER_SHOVEL string @readonly
---@field PREFAB_TOOL_HERBALIST_SICKLE string @readonly
---@field PREFAB_TOOL_SHEPHERD_STICK string @readonly
---@field PREFAB_TOOL_STONECUTTER_PICKAXE string @readonly
---@field PREFAB_TOOL_TAILOR_SCISSORS string @readonly
---@field PREFAB_TOOL_WOODCUTTER_AXE string @readonly
---@field PREFAB_TREE_BEECH string @readonly
---@field PREFAB_TREE_BEECH_2 string @readonly
---@field PREFAB_TREE_BIRCH string @readonly
---@field PREFAB_TREE_BIRCH_2 string @readonly
---@field PREFAB_TREE_CEDAR string @readonly
---@field PREFAB_TREE_ELM string @readonly
---@field PREFAB_TREE_ELM_2 string @readonly
---@field PREFAB_TREE_FIR string @readonly
---@field PREFAB_TREE_FIR_2 string @readonly
---@field PREFAB_TREE_OAK string @readonly
---@field PREFAB_TREE_OAK_2 string @readonly
---@field PREFAB_TREE_SYCAMORE string @readonly
---@field PREFAB_TREE_SYCAMORE_2 string @readonly

---@type PREFABS
_G.PREFABS = PREFABS