---@meta

---Enum for specific Quest identifiers.
---@class QUESTS
---@field NARRATIVE_LABOURBREWER_QST_GIVEHOPS_CLOTHING string @readonly
---@field NARRATIVE_LABOURBREWER_QST_GIVEHOPS_CLOTHING_HIGH string @readonly
---@field NARRATIVE_LABOURBREWER_QST_GIVEHOPS_FLOUR string @readonly
---@field NARRATIVE_LABOURBREWER_QST_GIVEHOPS_FLOUR_HIGH string @readonly
---@field NARRATIVE_LABOURBREWER_QST_GIVEHOPS_IRON string @readonly
---@field NARRATIVE_LABOURBREWER_QST_GIVEHOPS_IRON_HIGH string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDBEER_CLOTH string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDBEER_CLOTH_HIGH string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDBEER_PLANK string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDBEER_PLANK_HIGH string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDBEER_POLISHEDSTONE string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDBEER_POLISHEDSTONE_HIGH string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDBEER_TOOL string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDBEER_TOOL_HIGH string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDHOPS_BERRY string @readonly
---@field NARRATIVE_LABOURBREWER_QST_NEEDHOPS_WHEAT string @readonly
---@field ONBOARDING_QST_ASSIGNBUILDER string @readonly
---@field ONBOARDING_QST_BUILDBUILDER string @readonly
---@field ONBOARDING_QST_BUILDWAREHOUSE string @readonly
---@field ONBOARDING_QST_BUILDWOODCUTTER string @readonly
---@field ONBOARDING_QST_FILLNEEDS string @readonly
---@field ONBOARDING_QST_IMMIGRATION string @readonly
---@field ONBOARDING_QST_MANOR string @readonly
---@field ONBOARDING_QST_PAINTEXTRACTION string @readonly
---@field ONBOARDING_QST_PRODUCEBERRY string @readonly
---@field ONBOARDING_QST_RESIDENTIAL string @readonly
---@field ONBOARDING_QST_TRADE string @readonly
---@field QUEST_ADVANCEDONBOARDING_BAILIFFMANDATES string @readonly
---@field QUEST_ADVANCEDONBOARDING_CLERGYINFLUENCE_DELIVER string @readonly
---@field QUEST_ADVANCEDONBOARDING_CLERGYINFLUENCE_FLAG string @readonly
---@field QUEST_ADVANCEDONBOARDING_COMMONERPROMOTION string @readonly
---@field QUEST_ADVANCEDONBOARDING_CRAFTINGRATIONS string @readonly
---@field QUEST_ADVANCEDONBOARDING_CRAFTINGSPEARS_BOW string @readonly
---@field QUEST_ADVANCEDONBOARDING_CRAFTINGSPEARS_SPEAR string @readonly
---@field QUEST_ADVANCEDONBOARDING_CRAFTINGSPEARS_SWORD string @readonly
---@field QUEST_ADVANCEDONBOARDING_ENACTLEVY string @readonly
---@field QUEST_ADVANCEDONBOARDING_ESTATESPECIALIZATION_CLERGY string @readonly
---@field QUEST_ADVANCEDONBOARDING_ESTATESPECIALIZATION_KINGDOM string @readonly
---@field QUEST_ADVANCEDONBOARDING_ESTATESPECIALIZATION_LABOUR string @readonly
---@field QUEST_ADVANCEDONBOARDING_FIRSTEDICT string @readonly
---@field QUEST_ADVANCEDONBOARDING_FIRSTPRIVILEGE_CLERGY string @readonly
---@field QUEST_ADVANCEDONBOARDING_FIRSTPRIVILEGE_KINGDOM string @readonly
---@field QUEST_ADVANCEDONBOARDING_FIRSTPRIVILEGE_LABOUR string @readonly
---@field QUEST_ADVANCEDONBOARDING_HOUSEDENSITYINCREASE_PATROLLERS string @readonly
---@field QUEST_ADVANCEDONBOARDING_HOUSEDENSITYINCREASE_SOLDIERS string @readonly
---@field QUEST_ADVANCEDONBOARDING_KINGDOMINFLUENCE_FLAG string @readonly
---@field QUEST_ADVANCEDONBOARDING_LABOURINFLUENCE_DELIVER string @readonly
---@field QUEST_ADVANCEDONBOARDING_LABOURINFLUENCE_FLAG string @readonly
---@field QUEST_ADVANCEDONBOARDING_MONASTERYINFLUENCE_MONK string @readonly
---@field QUEST_ADVANCEDONBOARDING_MONASTERYINFLUENCE_NUN string @readonly
---@field QUEST_ADVANCEDONBOARDING_MONASTERYTRADEHERBS string @readonly
---@field QUEST_ADVANCEDONBOARDING_NEWTAX string @readonly
---@field QUEST_ADVANCEDONBOARDING_NOTOOLS string @readonly
---@field QUEST_ADVANCEDONBOARDING_PREPARECOMPANY string @readonly
---@field QUEST_ADVANCEDONBOARDING_PROSPERITY string @readonly
---@field QUEST_ADVANCEDONBOARDING_SECONDCOMPANY_BOW string @readonly
---@field QUEST_ADVANCEDONBOARDING_SECONDCOMPANY_SPEAR string @readonly
---@field QUEST_ADVANCEDONBOARDING_SECONDCOMPANY_SWORD string @readonly
---@field QUEST_ADVANCEDONBOARDING_SECONDFOOD string @readonly
---@field QUEST_ADVANCEDONBOARDING_STARTINGCASTLE string @readonly
---@field QUEST_ADVANCEDONBOARDING_STARTINGCASTLE_FLAG string @readonly
---@field QUEST_ADVANCEDONBOARDING_STARTINGMANORHOUSE string @readonly
---@field QUEST_ADVANCEDONBOARDING_STARTINGMONASTERY_MIXED string @readonly
---@field QUEST_ADVANCEDONBOARDING_STARTINGMONASTERY_MONK string @readonly
---@field QUEST_ADVANCEDONBOARDING_STARTINGMONASTERY_NUN string @readonly
---@field QUEST_ADVANCEDONBOARDING_TAXATIONLOWCOINS string @readonly
---@field QUEST_ADVANCEDONBOARDING_TAXATIONLOWHAPPINESS string @readonly
---@field QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_CASTLE string @readonly
---@field QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_MANOR_HOUSE string @readonly
---@field QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_MONASTERY string @readonly
---@field QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_VILLAGE_CENTRE string @readonly
---@field QUEST_ADVANCEDONBOARDING_VILLAGERLEAVING string @readonly
---@field QUEST_ADVANCEDONBOARDING_VISITHOSPITIUM_BUILD string @readonly
---@field QUEST_ADVANCEDONBOARDING_WOODCUTTEREXPANSION string @readonly
---@field QUEST_ASPIRATION_KINGDOM_STEP_1 string @readonly
---@field QUEST_ASPIRATION_KINGDOM_STEP_2 string @readonly
---@field QUEST_ASPIRATION_KINGDOM_STEP_3 string @readonly
---@field QUEST_ASPIRATION_KINGDOM_STEP_4 string @readonly
---@field QUEST_ASPIRATION_LABOUR_STEP_1 string @readonly
---@field QUEST_ASPIRATION_LABOUR_STEP_1_MANDATE string @readonly
---@field QUEST_ASPIRATION_LABOUR_STEP_2 string @readonly
---@field QUEST_ASPIRATION_LABOUR_STEP_3 string @readonly
---@field QUEST_ASPIRATION_LABOUR_STEP_4 string @readonly
---@field QUEST_ASPIRATION_MONASTERY_STEP_1 string @readonly
---@field QUEST_ASPIRATION_MONASTERY_STEP_2 string @readonly
---@field QUEST_ASPIRATION_MONASTERY_STEP_3 string @readonly
---@field QUEST_ASPIRATION_MONASTERY_STEP_4 string @readonly
---@field QUEST_ESTATE_TRADER_ORE_CLERGY_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_ORE_CLERGY_LOW string @readonly
---@field QUEST_ESTATE_TRADER_ORE_CLERGY_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_ORE_KINGDOM_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_ORE_KINGDOM_LOW string @readonly
---@field QUEST_ESTATE_TRADER_ORE_KINGDOM_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_ORE_LABOUR_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_ORE_LABOUR_LOW string @readonly
---@field QUEST_ESTATE_TRADER_ORE_LABOUR_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_WHEAT_CLERGY_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_WHEAT_CLERGY_LOW string @readonly
---@field QUEST_ESTATE_TRADER_WHEAT_CLERGY_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_WHEAT_KINGDOM_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_WHEAT_KINGDOM_LOW string @readonly
---@field QUEST_ESTATE_TRADER_WHEAT_KINGDOM_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_WHEAT_LABOUR_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_WHEAT_LABOUR_LOW string @readonly
---@field QUEST_ESTATE_TRADER_WHEAT_LABOUR_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_WOOD_CLERGY_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_WOOD_CLERGY_LOW string @readonly
---@field QUEST_ESTATE_TRADER_WOOD_CLERGY_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_WOOD_KINGDOM_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_WOOD_KINGDOM_LOW string @readonly
---@field QUEST_ESTATE_TRADER_WOOD_KINGDOM_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_WOOD_LABOUR_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_WOOD_LABOUR_LOW string @readonly
---@field QUEST_ESTATE_TRADER_WOOD_LABOUR_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_WOOL_CLERGY_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_WOOL_CLERGY_LOW string @readonly
---@field QUEST_ESTATE_TRADER_WOOL_CLERGY_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_WOOL_KINGDOM_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_WOOL_KINGDOM_LOW string @readonly
---@field QUEST_ESTATE_TRADER_WOOL_KINGDOM_STANDARD string @readonly
---@field QUEST_ESTATE_TRADER_WOOL_LABOUR_HIGH string @readonly
---@field QUEST_ESTATE_TRADER_WOOL_LABOUR_LOW string @readonly
---@field QUEST_ESTATE_TRADER_WOOL_LABOUR_STANDARD string @readonly
---@field QUEST_KINGDOM_HOSTING_KING_SUMMON string @readonly
---@field QUEST_KINGDOM_HOSTING_KING_SUMMON_FLAG string @readonly
---@field QUEST_KINGDOM_HOSTING_SWITCH_FLAG string @readonly
---@field QUEST_KINGDOM_HOSTING_WELCOME_FLAG string @readonly
---@field QUEST_KINGDOM_KING_HOSTING_EVENT_2_A string @readonly
---@field QUEST_KINGDOM_KING_HOSTING_SUMMON string @readonly
---@field QUEST_KINGDOM_WAR_COMPLETION_FLAG string @readonly
---@field QUEST_KINGDOM_WAR_INTRO_1 string @readonly
---@field QUEST_KINGDOM_WAR_INTRO_2 string @readonly
---@field QUEST_KINGDOM_WAR_RECURRING_FLAG string @readonly
---@field QUEST_KINGDOM_WAR_SUMMON string @readonly
---@field QUEST_KINGDOM_WAR_UNLOCK_FLAG string @readonly
---@field QUEST_KINGDOM_WELCOME_FLAG string @readonly
---@field QUEST_LABOURFAIR_BERRY_FAIR_CITY_MARKET string @readonly
---@field QUEST_LABOURFAIR_BERRY_FAIR_VILLAGE_MARKET string @readonly
---@field QUEST_LABOURFAIR_BREAD_FAIR_CITY_MARKET string @readonly
---@field QUEST_LABOURFAIR_BREAD_FAIR_VILLAGE_MARKET string @readonly
---@field QUEST_LABOURFAIR_FISH_FAIR_CITY_MARKET string @readonly
---@field QUEST_LABOURFAIR_FISH_FAIR_VILLAGE_MARKET string @readonly
---@field QUEST_LABOURFAIR_MARKETSPLENDOR string @readonly
---@field QUEST_LABOURFAIR_REGIONFAIR string @readonly
---@field QUEST_LABOURFAIR_VILLAGEHAPPINESS string @readonly
---@field QUEST_LABOUR_LODGING_FLAG string @readonly
---@field QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_1_A string @readonly
---@field QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_1_B string @readonly
---@field QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_1_C string @readonly
---@field QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_2_A string @readonly
---@field QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_2_B string @readonly
---@field QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_2_C string @readonly
---@field QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_3_A string @readonly
---@field QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_3_B string @readonly
---@field QUEST_LABOUR_SENESCHAL_HOSTING_MANDATE string @readonly
---@field QUEST_MONASTERYBREAD_GIVEBREAD string @readonly
---@field QUEST_MONASTERYBREAD_GIVEBREAD_HIGH string @readonly
---@field QUEST_MONASTERYBREAD_LOWINFLUENCE string @readonly
---@field QUEST_MONASTERYBREAD_NEEDBREAD string @readonly
---@field QUEST_MONASTERYBREAD_NEEDBREAD_HIGH string @readonly
---@field QUEST_MONASTERYHOSTING_EARLYDELIVERY_T1 string @readonly
---@field QUEST_MONASTERYHOSTING_EARLYDELIVERY_T2 string @readonly
---@field QUEST_MONASTERYHOSTING_EARLYDELIVERY_T3 string @readonly
---@field QUEST_MONASTERYHOSTING_EARLYDELIVERY_T4 string @readonly
---@field QUEST_MONASTERYHOSTING_EARLYDELIVERY_T5 string @readonly
---@field QUEST_MONASTERYHOSTING_FLAG string @readonly
---@field QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T1 string @readonly
---@field QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T2 string @readonly
---@field QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T3 string @readonly
---@field QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T4 string @readonly
---@field QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T5 string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_BARREL string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_BARREL_HIGH string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_LOW_INFLUENCE string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_POLISHEDSTONE string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_POLISHEDSTONE_HIGH string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_SCULPTURE string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_SCULPTURE_HIGH string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_STAINEDGLASS string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_STAINEDGLASS_HIGH string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_TOOL string @readonly
---@field QUEST_MONASTERYMANUSCRIPT_TOOL_HIGH string @readonly
---@field QUEST_MONASTERYTRADE_DIPLOMATIC string @readonly
---@field QUEST_MONASTERYTRADE_FLAG string @readonly
---@field QUEST_MONASTERYTRADE_TRADE_INCREASE_BARREL string @readonly
---@field QUEST_MONASTERYTRADE_TRADE_INCREASE_CHEESE string @readonly
---@field QUEST_MONASTERYTRADE_TRADE_INCREASE_POLISHEDSTONE string @readonly
---@field QUEST_MONASTERYTRADE_TRADE_SURPLUS_DONATED string @readonly
---@field QUEST_MONASTERYTRADE_TRADE_SURPLUS_SOLD string @readonly
---@field QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_A_GOLD string @readonly
---@field QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_A_WAX_HONEY string @readonly
---@field QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_B_MANUSCRIPT string @readonly
---@field QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_B_MATERIAL string @readonly
---@field QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_C_BERRY string @readonly
---@field QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_C_HERB string @readonly
---@field QUEST_MONASTERY_WINE_FLAG string @readonly
---@field QUEST_TOOLS_LOAN string @readonly
---@field QUEST_TOWNTALE_FLAG string @readonly
---@field QUEST_TRADETAXATION string @readonly
---@field QUEST_TRADETAXATION_FLAG string @readonly

local QUESTS = {
    NARRATIVE_LABOURBREWER_QST_GIVEHOPS_CLOTHING = "NARRATIVE_LABOURBREWER_QST_GIVEHOPS_CLOTHING",
    NARRATIVE_LABOURBREWER_QST_GIVEHOPS_CLOTHING_HIGH = "NARRATIVE_LABOURBREWER_QST_GIVEHOPS_CLOTHING_HIGH",
    NARRATIVE_LABOURBREWER_QST_GIVEHOPS_FLOUR = "NARRATIVE_LABOURBREWER_QST_GIVEHOPS_FLOUR",
    NARRATIVE_LABOURBREWER_QST_GIVEHOPS_FLOUR_HIGH = "NARRATIVE_LABOURBREWER_QST_GIVEHOPS_FLOUR_HIGH",
    NARRATIVE_LABOURBREWER_QST_GIVEHOPS_IRON = "NARRATIVE_LABOURBREWER_QST_GIVEHOPS_IRON",
    NARRATIVE_LABOURBREWER_QST_GIVEHOPS_IRON_HIGH = "NARRATIVE_LABOURBREWER_QST_GIVEHOPS_IRON_HIGH",
    NARRATIVE_LABOURBREWER_QST_NEEDBEER_CLOTH = "NARRATIVE_LABOURBREWER_QST_NEEDBEER_CLOTH",
    NARRATIVE_LABOURBREWER_QST_NEEDBEER_CLOTH_HIGH = "NARRATIVE_LABOURBREWER_QST_NEEDBEER_CLOTH_HIGH",
    NARRATIVE_LABOURBREWER_QST_NEEDBEER_PLANK = "NARRATIVE_LABOURBREWER_QST_NEEDBEER_PLANK",
    NARRATIVE_LABOURBREWER_QST_NEEDBEER_PLANK_HIGH = "NARRATIVE_LABOURBREWER_QST_NEEDBEER_PLANK_HIGH",
    NARRATIVE_LABOURBREWER_QST_NEEDBEER_POLISHEDSTONE = "NARRATIVE_LABOURBREWER_QST_NEEDBEER_POLISHEDSTONE",
    NARRATIVE_LABOURBREWER_QST_NEEDBEER_POLISHEDSTONE_HIGH = "NARRATIVE_LABOURBREWER_QST_NEEDBEER_POLISHEDSTONE_HIGH",
    NARRATIVE_LABOURBREWER_QST_NEEDBEER_TOOL = "NARRATIVE_LABOURBREWER_QST_NEEDBEER_TOOL",
    NARRATIVE_LABOURBREWER_QST_NEEDBEER_TOOL_HIGH = "NARRATIVE_LABOURBREWER_QST_NEEDBEER_TOOL_HIGH",
    NARRATIVE_LABOURBREWER_QST_NEEDHOPS_BERRY = "NARRATIVE_LABOURBREWER_QST_NEEDHOPS_BERRY",
    NARRATIVE_LABOURBREWER_QST_NEEDHOPS_WHEAT = "NARRATIVE_LABOURBREWER_QST_NEEDHOPS_WHEAT",
    ONBOARDING_QST_ASSIGNBUILDER = "ONBOARDING_QST_ASSIGNBUILDER",
    ONBOARDING_QST_BUILDBUILDER = "ONBOARDING_QST_BUILDBUILDER",
    ONBOARDING_QST_BUILDWAREHOUSE = "ONBOARDING_QST_BUILDWAREHOUSE",
    ONBOARDING_QST_BUILDWOODCUTTER = "ONBOARDING_QST_BUILDWOODCUTTER",
    ONBOARDING_QST_FILLNEEDS = "ONBOARDING_QST_FILLNEEDS",
    ONBOARDING_QST_IMMIGRATION = "ONBOARDING_QST_IMMIGRATION",
    ONBOARDING_QST_MANOR = "ONBOARDING_QST_MANOR",
    ONBOARDING_QST_PAINTEXTRACTION = "ONBOARDING_QST_PAINTEXTRACTION",
    ONBOARDING_QST_PRODUCEBERRY = "ONBOARDING_QST_PRODUCEBERRY",
    ONBOARDING_QST_RESIDENTIAL = "ONBOARDING_QST_RESIDENTIAL",
    ONBOARDING_QST_TRADE = "ONBOARDING_QST_TRADE",
    QUEST_ADVANCEDONBOARDING_BAILIFFMANDATES = "QUEST_ADVANCEDONBOARDING_BAILIFFMANDATES",
    QUEST_ADVANCEDONBOARDING_CLERGYINFLUENCE_DELIVER = "QUEST_ADVANCEDONBOARDING_CLERGYINFLUENCE_DELIVER",
    QUEST_ADVANCEDONBOARDING_CLERGYINFLUENCE_FLAG = "QUEST_ADVANCEDONBOARDING_CLERGYINFLUENCE_FLAG",
    QUEST_ADVANCEDONBOARDING_COMMONERPROMOTION = "QUEST_ADVANCEDONBOARDING_COMMONERPROMOTION",
    QUEST_ADVANCEDONBOARDING_CRAFTINGRATIONS = "QUEST_ADVANCEDONBOARDING_CRAFTINGRATIONS",
    QUEST_ADVANCEDONBOARDING_CRAFTINGSPEARS_BOW = "QUEST_ADVANCEDONBOARDING_CRAFTINGSPEARS_BOW",
    QUEST_ADVANCEDONBOARDING_CRAFTINGSPEARS_SPEAR = "QUEST_ADVANCEDONBOARDING_CRAFTINGSPEARS_SPEAR",
    QUEST_ADVANCEDONBOARDING_CRAFTINGSPEARS_SWORD = "QUEST_ADVANCEDONBOARDING_CRAFTINGSPEARS_SWORD",
    QUEST_ADVANCEDONBOARDING_ENACTLEVY = "QUEST_ADVANCEDONBOARDING_ENACTLEVY",
    QUEST_ADVANCEDONBOARDING_ESTATESPECIALIZATION_CLERGY = "QUEST_ADVANCEDONBOARDING_ESTATESPECIALIZATION_CLERGY",
    QUEST_ADVANCEDONBOARDING_ESTATESPECIALIZATION_KINGDOM = "QUEST_ADVANCEDONBOARDING_ESTATESPECIALIZATION_KINGDOM",
    QUEST_ADVANCEDONBOARDING_ESTATESPECIALIZATION_LABOUR = "QUEST_ADVANCEDONBOARDING_ESTATESPECIALIZATION_LABOUR",
    QUEST_ADVANCEDONBOARDING_FIRSTEDICT = "QUEST_ADVANCEDONBOARDING_FIRSTEDICT",
    QUEST_ADVANCEDONBOARDING_FIRSTPRIVILEGE_CLERGY = "QUEST_ADVANCEDONBOARDING_FIRSTPRIVILEGE_CLERGY",
    QUEST_ADVANCEDONBOARDING_FIRSTPRIVILEGE_KINGDOM = "QUEST_ADVANCEDONBOARDING_FIRSTPRIVILEGE_KINGDOM",
    QUEST_ADVANCEDONBOARDING_FIRSTPRIVILEGE_LABOUR = "QUEST_ADVANCEDONBOARDING_FIRSTPRIVILEGE_LABOUR",
    QUEST_ADVANCEDONBOARDING_HOUSEDENSITYINCREASE_PATROLLERS = "QUEST_ADVANCEDONBOARDING_HOUSEDENSITYINCREASE_PATROLLERS",
    QUEST_ADVANCEDONBOARDING_HOUSEDENSITYINCREASE_SOLDIERS = "QUEST_ADVANCEDONBOARDING_HOUSEDENSITYINCREASE_SOLDIERS",
    QUEST_ADVANCEDONBOARDING_KINGDOMINFLUENCE_FLAG = "QUEST_ADVANCEDONBOARDING_KINGDOMINFLUENCE_FLAG",
    QUEST_ADVANCEDONBOARDING_LABOURINFLUENCE_DELIVER = "QUEST_ADVANCEDONBOARDING_LABOURINFLUENCE_DELIVER",
    QUEST_ADVANCEDONBOARDING_LABOURINFLUENCE_FLAG = "QUEST_ADVANCEDONBOARDING_LABOURINfluence_FLAG",
    QUEST_ADVANCEDONBOARDING_MONASTERYINFLUENCE_MONK = "QUEST_ADVANCEDONBOARDING_MONASTERYINFLUENCE_MONK",
    QUEST_ADVANCEDONBOARDING_MONASTERYINFLUENCE_NUN = "QUEST_ADVANCEDONBOARDING_MONASTERYINFLUENCE_NUN",
    QUEST_ADVANCEDONBOARDING_MONASTERYTRADEHERBS = "QUEST_ADVANCEDONBOARDING_MONASTERYTRADEHERBS",
    QUEST_ADVANCEDONBOARDING_NEWTAX = "QUEST_ADVANCEDONBOARDING_NEWTAX",
    QUEST_ADVANCEDONBOARDING_NOTOOLS = "QUEST_ADVANCEDONBOARDING_NOTOOLS",
    QUEST_ADVANCEDONBOARDING_PREPARECOMPANY = "QUEST_ADVANCEDONBOARDING_PREPARECOMPANY",
    QUEST_ADVANCEDONBOARDING_PROSPERITY = "QUEST_ADVANCEDONBOARDING_PROSPERITY",
    QUEST_ADVANCEDONBOARDING_SECONDCOMPANY_BOW = "QUEST_ADVANCEDONBOARDING_SECONDCOMPANY_BOW",
    QUEST_ADVANCEDONBOARDING_SECONDCOMPANY_SPEAR = "QUEST_ADVANCEDONBOARDING_SECONDCOMPANY_SPEAR",
    QUEST_ADVANCEDONBOARDING_SECONDCOMPANY_SWORD = "QUEST_ADVANCEDONBOARDING_SECONDCOMPANY_SWORD",
    QUEST_ADVANCEDONBOARDING_SECONDFOOD = "QUEST_ADVANCEDONBOARDING_SECONDFOOD",
    QUEST_ADVANCEDONBOARDING_STARTINGCASTLE = "QUEST_ADVANCEDONBOARDING_STARTINGCASTLE",
    QUEST_ADVANCEDONBOARDING_STARTINGCASTLE_FLAG = "QUEST_ADVANCEDONBOARDING_STARTINGCASTLE_FLAG",
    QUEST_ADVANCEDONBOARDING_STARTINGMANORHOUSE = "QUEST_ADVANCEDONBOARDING_STARTINGMANORHOUSE",
    QUEST_ADVANCEDONBOARDING_STARTINGMONASTERY_MIXED = "QUEST_ADVANCEDONBOARDING_STARTINGMONASTERY_MIXED",
    QUEST_ADVANCEDONBOARDING_STARTINGMONASTERY_MONK = "QUEST_ADVANCEDONBOARDING_STARTINGMONASTERY_MONK",
    QUEST_ADVANCEDONBOARDING_STARTINGMONASTERY_NUN = "QUEST_ADVANCEDONBOARDING_STARTINGMONASTERY_NUN",
    QUEST_ADVANCEDONBOARDING_TAXATIONLOWCOINS = "QUEST_ADVANCEDONBOARDING_TAXATIONLOWCOINS",
    QUEST_ADVANCEDONBOARDING_TAXATIONLOWHAPPINESS = "QUEST_ADVANCEDONBOARDING_TAXATIONLOWHAPPINESS",
    QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_CASTLE = "QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_CASTLE",
    QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_MANOR_HOUSE = "QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_MANOR_HOUSE",
    QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_MONASTERY = "QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_MONASTERY",
    QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_VILLAGE_CENTRE = "QUEST_ADVANCEDONBOARDING_UPGRADINGTRADEROUTE_VILLAGE_CENTRE",
    QUEST_ADVANCEDONBOARDING_VILLAGERLEAVING = "QUEST_ADVANCEDONBOARDING_VILLAGERLEAVING",
    QUEST_ADVANCEDONBOARDING_VISITHOSPITIUM_BUILD = "QUEST_ADVANCEDONBOARDING_VISITHOSPITIUM_BUILD",
    QUEST_ADVANCEDONBOARDING_WOODCUTTEREXPANSION = "QUEST_ADVANCEDONBOARDING_WOODCUTTEREXPANSION",
    QUEST_ASPIRATION_KINGDOM_STEP_1 = "QUEST_ASPIRATION_KINGDOM_STEP_1",
    QUEST_ASPIRATION_KINGDOM_STEP_2 = "QUEST_ASPIRATION_KINGDOM_STEP_2",
    QUEST_ASPIRATION_KINGDOM_STEP_3 = "QUEST_ASPIRATION_KINGDOM_STEP_3",
    QUEST_ASPIRATION_KINGDOM_STEP_4 = "QUEST_ASPIRATION_KINGDOM_STEP_4",
    QUEST_ASPIRATION_LABOUR_STEP_1 = "QUEST_ASPIRATION_LABOUR_STEP_1",
    QUEST_ASPIRATION_LABOUR_STEP_1_MANDATE = "QUEST_ASPIRATION_LABOUR_STEP_1_MANDATE",
    QUEST_ASPIRATION_LABOUR_STEP_2 = "QUEST_ASPIRATION_LABOUR_STEP_2",
    QUEST_ASPIRATION_LABOUR_STEP_3 = "QUEST_ASPIRATION_LABOUR_STEP_3",
    QUEST_ASPIRATION_LABOUR_STEP_4 = "QUEST_ASPIRATION_LABOUR_STEP_4",
    QUEST_ASPIRATION_MONASTERY_STEP_1 = "QUEST_ASPIRATION_MONASTERY_STEP_1",
    QUEST_ASPIRATION_MONASTERY_STEP_2 = "QUEST_ASPIRATION_MONASTERY_STEP_2",
    QUEST_ASPIRATION_MONASTERY_STEP_3 = "QUEST_ASPIRATION_MONASTERY_STEP_3",
    QUEST_ASPIRATION_MONASTERY_STEP_4 = "QUEST_ASPIRATION_MONASTERY_STEP_4",
    QUEST_ESTATE_TRADER_ORE_CLERGY_HIGH = "QUEST_ESTATE_TRADER_ORE_CLERGY_HIGH",
    QUEST_ESTATE_TRADER_ORE_CLERGY_LOW = "QUEST_ESTATE_TRADER_ORE_CLERGY_LOW",
    QUEST_ESTATE_TRADER_ORE_CLERGY_STANDARD = "QUEST_ESTATE_TRADER_ORE_CLERGY_STANDARD",
    QUEST_ESTATE_TRADER_ORE_KINGDOM_HIGH = "QUEST_ESTATE_TRADER_ORE_KINGDOM_HIGH",
    QUEST_ESTATE_TRADER_ORE_KINGDOM_LOW = "QUEST_ESTATE_TRADER_ORE_KINGDOM_LOW",
    QUEST_ESTATE_TRADER_ORE_KINGDOM_STANDARD = "QUEST_ESTATE_TRADER_ORE_KINGDOM_STANDARD",
    QUEST_ESTATE_TRADER_ORE_LABOUR_HIGH = "QUEST_ESTATE_TRADER_ORE_LABOUR_HIGH",
    QUEST_ESTATE_TRADER_ORE_LABOUR_LOW = "QUEST_ESTATE_TRADER_ORE_LABOUR_LOW",
    QUEST_ESTATE_TRADER_ORE_LABOUR_STANDARD = "QUEST_ESTATE_TRADER_ORE_LABOUR_STANDARD",
    QUEST_ESTATE_TRADER_WHEAT_CLERGY_HIGH = "QUEST_ESTATE_TRADER_WHEAT_CLERGY_HIGH",
    QUEST_ESTATE_TRADER_WHEAT_CLERGY_LOW = "QUEST_ESTATE_TRADER_WHEAT_CLERGY_LOW",
    QUEST_ESTATE_TRADER_WHEAT_CLERGY_STANDARD = "QUEST_ESTATE_TRADER_WHEAT_CLERGY_STANDARD",
    QUEST_ESTATE_TRADER_WHEAT_KINGDOM_HIGH = "QUEST_ESTATE_TRADER_WHEAT_KINGDOM_HIGH",
    QUEST_ESTATE_TRADER_WHEAT_KINGDOM_LOW = "QUEST_ESTATE_TRADER_WHEAT_KINGDOM_LOW",
    QUEST_ESTATE_TRADER_WHEAT_KINGDOM_STANDARD = "QUEST_ESTATE_TRADER_WHEAT_KINGDOM_STANDARD",
    QUEST_ESTATE_TRADER_WHEAT_LABOUR_HIGH = "QUEST_ESTATE_TRADER_WHEAT_LABOUR_HIGH",
    QUEST_ESTATE_TRADER_WHEAT_LABOUR_LOW = "QUEST_ESTATE_TRADER_WHEAT_LABOUR_LOW",
    QUEST_ESTATE_TRADER_WHEAT_LABOUR_STANDARD = "QUEST_ESTATE_TRADER_WHEAT_LABOUR_STANDARD",
    QUEST_ESTATE_TRADER_WOOD_CLERGY_HIGH = "QUEST_ESTATE_TRADER_WOOD_CLERGY_HIGH",
    QUEST_ESTATE_TRADER_WOOD_CLERGY_LOW = "QUEST_ESTATE_TRADER_WOOD_CLERGY_LOW",
    QUEST_ESTATE_TRADER_WOOD_CLERGY_STANDARD = "QUEST_ESTATE_TRADER_WOOD_CLERGY_STANDARD",
    QUEST_ESTATE_TRADER_WOOD_KINGDOM_HIGH = "QUEST_ESTATE_TRADER_WOOD_KINGDOM_HIGH",
    QUEST_ESTATE_TRADER_WOOD_KINGDOM_LOW = "QUEST_ESTATE_TRADER_WOOD_KINGDOM_LOW",
    QUEST_ESTATE_TRADER_WOOD_KINGDOM_STANDARD = "QUEST_ESTATE_TRADER_WOOD_KINGDOM_STANDARD",
    QUEST_ESTATE_TRADER_WOOD_LABOUR_HIGH = "QUEST_ESTATE_TRADER_WOOD_LABOUR_HIGH",
    QUEST_ESTATE_TRADER_WOOD_LABOUR_LOW = "QUEST_ESTATE_TRADER_WOOD_LABOUR_LOW",
    QUEST_ESTATE_TRADER_WOOD_LABOUR_STANDARD = "QUEST_ESTATE_TRADER_WOOD_LABOUR_STANDARD",
    QUEST_ESTATE_TRADER_WOOL_CLERGY_HIGH = "QUEST_ESTATE_TRADER_WOOL_CLERGY_HIGH",
    QUEST_ESTATE_TRADER_WOOL_CLERGY_LOW = "QUEST_ESTATE_TRADER_WOOL_CLERGY_LOW",
    QUEST_ESTATE_TRADER_WOOL_CLERGY_STANDARD = "QUEST_ESTATE_TRADER_WOOL_CLERGY_STANDARD",
    QUEST_ESTATE_TRADER_WOOL_KINGDOM_HIGH = "QUEST_ESTATE_TRADER_WOOL_KINGDOM_HIGH",
    QUEST_ESTATE_TRADER_WOOL_KINGDOM_LOW = "QUEST_ESTATE_TRADER_WOOL_KINGDOM_LOW",
    QUEST_ESTATE_TRADER_WOOL_KINGDOM_STANDARD = "QUEST_ESTATE_TRADER_WOOL_KINGDOM_STANDARD",
    QUEST_ESTATE_TRADER_WOOL_LABOUR_HIGH = "QUEST_ESTATE_TRADER_WOOL_LABOUR_HIGH",
    QUEST_ESTATE_TRADER_WOOL_LABOUR_LOW = "QUEST_ESTATE_TRADER_WOOL_LABOUR_LOW",
    QUEST_ESTATE_TRADER_WOOL_LABOUR_STANDARD = "QUEST_ESTATE_TRADER_WOOL_LABOUR_STANDARD",
    QUEST_KINGDOM_HOSTING_KING_SUMMON = "QUEST_KINGDOM_HOSTING_KING_SUMMON",
    QUEST_KINGDOM_HOSTING_KING_SUMMON_FLAG = "QUEST_KINGDOM_HOSTING_KING_SUMMON_FLAG",
    QUEST_KINGDOM_HOSTING_SWITCH_FLAG = "QUEST_KINGDOM_HOSTING_SWITCH_FLAG",
    QUEST_KINGDOM_HOSTING_WELCOME_FLAG = "QUEST_KINGDOM_HOSTING_WELCOME_FLAG",
    QUEST_KINGDOM_KING_HOSTING_EVENT_2_A = "QUEST_KINGDOM_KING_HOSTING_EVENT_2_A",
    QUEST_KINGDOM_KING_HOSTING_SUMMON = "QUEST_KINGDOM_KING_HOSTING_SUMMON",
    QUEST_KINGDOM_WAR_COMPLETION_FLAG = "QUEST_KINGDOM_WAR_COMPLETION_FLAG",
    QUEST_KINGDOM_WAR_INTRO_1 = "QUEST_KINGDOM_WAR_INTRO_1",
    QUEST_KINGDOM_WAR_INTRO_2 = "QUEST_KINGDOM_WAR_INTRO_2",
    QUEST_KINGDOM_WAR_RECURRING_FLAG = "QUEST_KINGDOM_WAR_RECURRING_FLAG",
    QUEST_KINGDOM_WAR_SUMMON = "QUEST_KINGDOM_WAR_SUMMON",
    QUEST_KINGDOM_WAR_UNLOCK_FLAG = "QUEST_KINGDOM_WAR_UNLOCK_FLAG",
    QUEST_KINGDOM_WELCOME_FLAG = "QUEST_KINGDOM_WELCOME_FLAG",
    QUEST_LABOURFAIR_BERRY_FAIR_CITY_MARKET = "QUEST_LABOURFAIR_BERRY_FAIR_CITY_MARKET",
    QUEST_LABOURFAIR_BERRY_FAIR_VILLAGE_MARKET = "QUEST_LABOURFAIR_BERRY_FAIR_VILLAGE_MARKET",
    QUEST_LABOURFAIR_BREAD_FAIR_CITY_MARKET = "QUEST_LABOURFAIR_BREAD_FAIR_CITY_MARKET",
    QUEST_LABOURFAIR_BREAD_FAIR_VILLAGE_MARKET = "QUEST_LABOURFAIR_BREAD_FAIR_VILLAGE_MARKET",
    QUEST_LABOURFAIR_FISH_FAIR_CITY_MARKET = "QUEST_LABOURFAIR_FISH_FAIR_CITY_MARKET",
    QUEST_LABOURFAIR_FISH_FAIR_VILLAGE_MARKET = "QUEST_LABOURFAIR_FISH_FAIR_VILLAGE_MARKET",
    QUEST_LABOURFAIR_MARKETSPLENDOR = "QUEST_LABOURFAIR_MARKETSPLENDOR",
    QUEST_LABOURFAIR_REGIONFAIR = "QUEST_LABOURFAIR_REGIONFAIR",
    QUEST_LABOURFAIR_VILLAGEHAPPINESS = "QUEST_LABOURFAIR_VILLAGEHAPPINESS",
    QUEST_LABOUR_LODGING_FLAG = "QUEST_LABOUR_LODGING_FLAG",
    QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_1_A = "QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_1_A",
    QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_1_B = "QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_1_B",
    QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_1_C = "QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_1_C",
    QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_2_A = "QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_2_A",
    QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_2_B = "QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_2_B",
    QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_2_C = "QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_2_C",
    QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_3_A = "QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_3_A",
    QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_3_B = "QUEST_LABOUR_SENESCHAL_HOSTING_EVENT_3_B",
    QUEST_LABOUR_SENESCHAL_HOSTING_MANDATE = "QUEST_LABOUR_SENESCHAL_HOSTING_MANDATE",
    QUEST_MONASTERYBREAD_GIVEBREAD = "QUEST_MONASTERYBREAD_GIVEBREAD",
    QUEST_MONASTERYBREAD_GIVEBREAD_HIGH = "QUEST_MONASTERYBREAD_GIVEBREAD_HIGH",
    QUEST_MONASTERYBREAD_LOWINFLUENCE = "QUEST_MONASTERYBREAD_LOWINFLUENCE",
    QUEST_MONASTERYBREAD_NEEDBREAD = "QUEST_MONASTERYBREAD_NEEDBREAD",
    QUEST_MONASTERYBREAD_NEEDBREAD_HIGH = "QUEST_MONASTERYBREAD_NEEDBREAD_HIGH",
    QUEST_MONASTERYHOSTING_EARLYDELIVERY_T1 = "QUEST_MONASTERYHOSTING_EARLYDELIVERY_T1",
    QUEST_MONASTERYHOSTING_EARLYDELIVERY_T2 = "QUEST_MONASTERYHOSTING_EARLYDELIVERY_T2",
    QUEST_MONASTERYHOSTING_EARLYDELIVERY_T3 = "QUEST_MONASTERYHOSTING_EARLYDELIVERY_T3",
    QUEST_MONASTERYHOSTING_EARLYDELIVERY_T4 = "QUEST_MONASTERYHOSTING_EARLYDELIVERY_T4",
    QUEST_MONASTERYHOSTING_EARLYDELIVERY_T5 = "QUEST_MONASTERYHOSTING_EARLYDELIVERY_T5",
    QUEST_MONASTERYHOSTING_FLAG = "QUEST_MONASTERYHOSTING_FLAG",
    QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T1 = "QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T1",
    QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T2 = "QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T2",
    QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T3 = "QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T3",
    QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T4 = "QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T4",
    QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T5 = "QUEST_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY_T5",
    QUEST_MONASTERYMANUSCRIPT_BARREL = "QUEST_MONASTERYMANUSCRIPT_BARREL",
    QUEST_MONASTERYMANUSCRIPT_BARREL_HIGH = "QUEST_MONASTERYMANUSCRIPT_BARREL_HIGH",
    QUEST_MONASTERYMANUSCRIPT_LOW_INFLUENCE = "QUEST_MONASTERYMANUSCRIPT_LOW_INFLUENCE",
    QUEST_MONASTERYMANUSCRIPT_POLISHEDSTONE = "QUEST_MONASTERYMANUSCRIPT_POLISHEDSTONE",
    QUEST_MONASTERYMANUSCRIPT_POLISHEDSTONE_HIGH = "QUEST_MONASTERYMANUSCRIPT_POLISHEDSTONE_HIGH",
    QUEST_MONASTERYMANUSCRIPT_SCULPTURE = "QUEST_MONASTERYMANUSCRIPT_SCULPTURE",
    QUEST_MONASTERYMANUSCRIPT_SCULPTURE_HIGH = "QUEST_MONASTERYMANUSCRIPT_SCULPTURE_HIGH",
    QUEST_MONASTERYMANUSCRIPT_STAINEDGLASS = "QUEST_MONASTERYMANUSCRIPT_STAINEDGLASS",
    QUEST_MONASTERYMANUSCRIPT_STAINEDGLASS_HIGH = "QUEST_MONASTERYMANUSCRIPT_STAINEDGLASS_HIGH",
    QUEST_MONASTERYMANUSCRIPT_TOOL = "QUEST_MONASTERYMANUSCRIPT_TOOL",
    QUEST_MONASTERYMANUSCRIPT_TOOL_HIGH = "QUEST_MONASTERYMANUSCRIPT_TOOL_HIGH",
    QUEST_MONASTERYTRADE_DIPLOMATIC = "QUEST_MONASTERYTRADE_DIPLOMATIC",
    QUEST_MONASTERYTRADE_FLAG = "QUEST_MONASTERYTRADE_FLAG",
    QUEST_MONASTERYTRADE_TRADE_INCREASE_BARREL = "QUEST_MONASTERYTRADE_TRADE_INCREASE_BARREL",
    QUEST_MONASTERYTRADE_TRADE_INCREASE_CHEESE = "QUEST_MONASTERYTRADE_TRADE_INCREASE_CHEESE",
    QUEST_MONASTERYTRADE_TRADE_INCREASE_POLISHEDSTONE = "QUEST_MONASTERYTRADE_TRADE_INCREASE_POLISHEDSTONE",
    QUEST_MONASTERYTRADE_TRADE_SURPLUS_DONATED = "QUEST_MONASTERYTRADE_TRADE_SURPLUS_DONATED",
    QUEST_MONASTERYTRADE_TRADE_SURPLUS_SOLD = "QUEST_MONASTERYTRADE_TRADE_SURPLUS_SOLD",
    QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_A_GOLD = "QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_A_GOLD",
    QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_A_WAX_HONEY = "QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_A_WAX_HONEY",
    QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_B_MANUSCRIPT = "QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_B_MANUSCRIPT",
    QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_B_MATERIAL = "QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_B_MATERIAL",
    QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_C_BERRY = "QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_C_BERRY",
    QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_C_HERB = "QUEST_MONASTERY_ABBESS_HOSTING_EVENT_2_C_HERB",
    QUEST_MONASTERY_WINE_FLAG = "QUEST_MONASTERY_WINE_FLAG",
    QUEST_TOOLS_LOAN = "QUEST_TOOLS_LOAN",
    QUEST_TOWNTALE_FLAG = "QUEST_TOWNTALE_FLAG",
    QUEST_TRADETAXATION = "QUEST_TRADETAXATION",
    QUEST_TRADETAXATION_FLAG = "QUEST_TRADETAXATION_FLAG",
}

---@type QUESTS
_G.QUESTS = QUESTS
