---@meta

---@class VILLAGER_STATUS_QUOTA : ASSET
---@field VillagerStatusRatioList list<VILLAGER_STATUS_RATIO> # List of VILLAGER_STATUS_RATIO values.

local VILLAGER_STATUS_QUOTA = {}

---@type VILLAGER_STATUS_QUOTA
_G.VILLAGER_STATUS_QUOTA = VILLAGER_STATUS_QUOTA
