---@meta

---
---Lua enum for agent need resource types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/agent_need_type_resource)
---
---@enum AGENT_NEED_TYPE_RESOURCE_ASSET
AGENT_NEED_TYPE_RESOURCE_ASSET = {
    NEED_ADDITIONAL_ENTERTAINMENT = "NEED_ADDITIONAL_ENTERTAINMENT",
    NEED_ADDITIONAL_FOOD_MONK = "NEED_ADDITIONAL_FOOD_MONK",
    NEED_ADDITIONAL_FOOD_REFINED = "NEED_ADDITIONAL_FOOD_REFINED",
    NEED_ADDITIONAL_GOODS = "NEED_ADDITIONAL_GOODS",
    NEED_ADDITIONAL_LUXURY = "NEED_ADDITIONAL_LUXURY",
    NEED_ADDITIONAL_SERVICE = "NEED_ADDITIONAL_SERVICE",
    NEED_ESSENTIAL_ENTERTAINMENT = "NEED_ESSENTIAL_ENTERTAINMENT",
    NEED_ESSENTIAL_FOOD_MONK = "NEED_ESSENTIAL_FOOD_MONK",
    NEED_ESSENTIAL_FOOD_REFINED = "NEED_ESSENTIAL_FOOD_REFINED",
    NEED_ESSENTIAL_FOOD_RUSTIC = "NEED_ESSENTIAL_FOOD_RUSTIC",
    NEED_ESSENTIAL_SERVICE = "NEED_ESSENTIAL_SERVICE",
    NEED_ESSENTIAL_SERVICE_MONK = "NEED_ESSENTIAL_SERVICE_MONK",
    NEED_ESSENTIAL_WATER = "NEED_ESSENTIAL_WATER",
    NEED_GUEST_ENTERTAINMENT = "NEED_GUEST_ENTERTAINMENT",
    NEED_GUEST_FOOD_MONASTIC = "NEED_GUEST_FOOD_MONASTIC",
    NEED_GUEST_FOOD_REFINED = "NEED_GUEST_FOOD_REFINED",
    NEED_GUEST_FOOD_RUSTIC = "NEED_GUEST_FOOD_RUSTIC",
    NEED_GUEST_FOOD_RUSTIC_HIGH = "NEED_GUEST_FOOD_RUSTIC_HIGH",
    NEED_GUEST_GOODS = "NEED_GUEST_GOODS",
    NEED_GUEST_GOODS_HIGH = "NEED_GUEST_GOODS_HIGH",
    NEED_GUEST_LUXURY = "NEED_GUEST_LUXURY",
    NEED_GUEST_LUXURY_HIGH = "NEED_GUEST_LUXURY_HIGH",
    NEED_GUEST_SERVICES = "NEED_GUEST_SERVICES",
    NEED_GUEST_SERVICES_HIGH = "NEED_GUEST_SERVICES_HIGH",
    NEED_GUEST_VISIT_WATER = "NEED_GUEST_VISIT_WATER",
}