---@meta

---
---Lua enum for agent_need_type_visit_building asset types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/agent_need_type_visit_building)
---
---@enum AGENT_NEED_TYPE_VISIT_BUILDING_ASSET
AGENT_NEED_TYPE_VISIT_BUILDING = {
    NEED_ADDITIONAL_CLOISTER = "NEED_ADDITIONAL_CLOISTER",
    NEED_GUEST_CLOISTER = "NEED_GUEST_CLOISTER",
    NEED_GUEST_VISIT_ABBATIAL = "NEED_GUEST_VISIT_ABBATIAL",
    NEED_GUEST_VISIT_APIARY = "NEED_GUEST_VISIT_APIARY",
    NEED_GUEST_VISIT_BUILDER_HIGH = "NEED_GUEST_VISIT_BUILDER_HIGH",
    NEED_GUEST_VISIT_GREAT_HALL = "NEED_GUEST_VISIT_GREAT_HALL",
    NEED_GUEST_VISIT_MONASTERY_KITCHEN = "NEED_GUEST_VISIT_MONASTERY_KITCHEN",
    NEED_GUEST_VISIT_SCRIPTORIUM = "NEED_GUEST_VISIT_SCRIPTORIUM",
    NEED_GUEST_VISIT_VINEYARD_HIGH = "NEED_GUEST_VISIT_VINEYARD_HIGH",
    NEED_GUEST_VISIT_WINERY_HIGH = "NEED_GUEST_VISIT_WINERY_HIGH",
}