---@meta

---
---List of assignable building functions.
---Lua enum for asset enum used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/assignable_building_function_list)
---
---@enum ASSIGNABLE_BUILDING_FUNCTION_LIST_ASSET
ASSIGNABLE_BUILDING_FUNCTION_LIST = {
    BUILDING_FUNCTION_BOWYER_LIST = "BUILDING_FUNCTION_BOWYER_LIST",
    BUILDING_FUNCTION_CASTLE_PROVISIONER_LIST = "BUILDING_FUNCTION_CASTLE_PROVISIONER_LIST",
    BUILDING_FUNCTION_MONASTERY_KITCHEN_LIST = "BUILDING_FUNCTION_MONASTERY_KITCHEN_LIST",
    BUILDING_FUNCTION_SPEARMAKER_LIST = "BUILDING_FUNCTION_SPEARMAKER_LIST",
    BUILDING_FUNCTION_SWORDSMITH_LIST = "BUILDING_FUNCTION_SWORDSMITH_LIST",
}