---@meta

---
---Lua enum for behavior tree assets used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/behavior_tree)
---
---@enum BEHAVIOR_TREE_ASSET
BEHAVIOR_TREE = {
    BEHAVIOR_BAILIFF = "BEHAVIOR_BAILIFF",
    BEHAVIOR_BUILDER = "BEHAVIOR_BUILDER",
    BEHAVIOR_BUILDER_CRAFTING = "BEHAVIOR_BUILDER_CRAFTING",
    BEHAVIOR_FARMER = "BEHAVIOR_FARMER",
    BEHAVIOR_FORESTER = "BEHAVIOR_FORESTER",
    BEHAVIOR_GATHER = "BEHAVIOR_GATHER",
    BEHAVIOR_GUEST = "BEHAVIOR_GUEST",
    BEHAVIOR_LEAVE_VILLAGE = "BEHAVIOR_LEAVE_VILLAGE",
    BEHAVIOR_LIVESTOCK = "BEHAVIOR_LIVESTOCK",
    BEHAVIOR_MARKET_TENDING = "BEHAVIOR_MARKET_TENDING",
    BEHAVIOR_PLANT = "BEHAVIOR_PLANT",
    BEHAVIOR_SOLDIER = "BEHAVIOR_SOLDIER",
    BEHAVIOR_SOLDIER_BACK = "BEHAVIOR_SOLDIER_BACK",
    BEHAVIOR_SOLDIER_GUARD = "BEHAVIOR_SOLDIER_GUARD",
    BEHAVIOR_SOLDIER_LEAVE = "BEHAVIOR_SOLDIER_LEAVE",
    BEHAVIOR_SOLDIER_REGROUP = "BEHAVIOR_SOLDIER_REGROUP",
    BEHAVIOR_SOLDIER_TRAINING = "BEHAVIOR_SOLDIER_TRAINING",
    BEHAVIOR_STUDY = "BEHAVIOR_STUDY",
    BEHAVIOR_TAX_COLLECTION = "BEHAVIOR_TAX_COLLECTION",
    BEHAVIOR_TRANSPORT = "BEHAVIOR_TRANSPORT",
    BEHAVIOR_TRANSPORTER = "BEHAVIOR_TRANSPORTER",
    BEHAVIOR_VILLAGER = "BEHAVIOR_VILLAGER",
    BEHAVIOR_VISITOR = "BEHAVIOR_VISITOR",
    BEHAVIOR_WORK = "BEHAVIOR_WORK",
}