---@meta

---
---BUILDING_GAME_CONDITION_CONFIG enum.
---Lua enum for asset enum types representing building game condition configurations used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/building_game_condition_config)
---
---@enum BUILDING_GAME_CONDITION_CONFIG_ASSET
BUILDING_GAME_CONDITION_CONFIG_ASSET = {
    BUILDING_GAME_CONDITION_CONFIG_FORTIFICATION_HEAVY = "BUILDING_GAME_CONDITION_CONFIG_FORTIFICATION_HEAVY",
    BUILDING_GAME_CONDITION_CONFIG_FORTIFICATION_LIGHT = "BUILDING_GAME_CONDITION_CONFIG_FORTIFICATION_LIGHT",
    BUILDING_GAME_CONDITION_CONFIG_INTERIOR_ACCESS = "BUILDING_GAME_CONDITION_CONFIG_INTERIOR_ACCESS",
}