---@meta

---
---BUILDING_FUNCTION
---Lua enum for building function asset types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/building_function)
---
---@enum BUILDING_FUNCTION_ASSET
BUILDING_FUNCTION = {
    BUILDING_FUNCTION_CANDLE_WORKSHOP_EXTENSION = "BUILDING_FUNCTION_CANDLE_WORKSHOP_EXTENSION",
    BUILDING_FUNCTION_COMMON_WARES_TOWER = "BUILDING_FUNCTION_COMMON_WARES_TOWER",
    BUILDING_FUNCTION_MONASTERY_CLOISTER = "BUILDING_FUNCTION_MONASTERY_CLOISTER",
    BUILDING_FUNCTION_STONEMASON_INPUT_IMPROVEMENT = "BUILDING_FUNCTION_STONEMASON_INPUT_IMPROVEMENT",

    BUILDING_FUNCTION_ACCOMMODATION = {
        BUILDING_FUNCTION_CASTLE_BARRACK_ASSIGNABLE = "BUILDING_FUNCTION_CASTLE_BARRACK_ASSIGNABLE",
        BUILDING_FUNCTION_CASTLE_QUARTERS_ASSIGNABLE = "BUILDING_FUNCTION_CASTLE_QUARTERS_ASSIGNABLE",
    },

    BUILDING_FUNCTION_ASSIGNABLE = {
        BUILDING_FUNCTION_BOWYER_ASSIGNABLE = "BUILDING_FUNCTION_BOWYER_ASSIGNABLE",
        BUILDING_FUNCTION_CASTLE_PROVISIONER_ASSIGNABLE = "BUILDING_FUNCTION_CASTLE_PROVISIONER_ASSIGNABLE",
        BUILDING_FUNCTION_MONASTERY_KITCHEN_ASSIGNABLE = "BUILDING_FUNCTION_MONASTERY_KITCHEN_ASSIGNABLE",
        BUILDING_FUNCTION_SPEARMAKER_ASSIGNABLE = "BUILDING_FUNCTION_SPEARMAKER_ASSIGNABLE",
        BUILDING_FUNCTION_SWORDSMITH_ASSIGNABLE = "BUILDING_FUNCTION_SWORDSMITH_ASSIGNABLE",
    },

    BUILDING_FUNCTION_BAILIFF_OFFICE = {
        BUILDING_FUNCTION_BAILIFF_OFFICE = "BUILDING_FUNCTION_BAILIFF_OFFICE",
        BUILDING_FUNCTION_CASTLE_ROYAL_OFFICE = "BUILDING_FUNCTION_CASTLE_ROYAL_OFFICE",
        BUILDING_FUNCTION_MONASTERY_EMISSARY_OFFICE = "BUILDING_FUNCTION_MONASTERY_EMISSARY_OFFICE",
    },

    BUILDING_FUNCTION_BUILDER_WORKSHOP = {
        BUILDING_FUNCTION_BUILDER_WORKSHOP = "BUILDING_FUNCTION_BUILDER_WORKSHOP",
    },

    BUILDING_FUNCTION_CHURCH = {
        BUILDING_FUNCTION_CHURCH = "BUILDING_FUNCTION_CHURCH",
        BUILDING_FUNCTION_MONASTERY_ABBATIAL = "BUILDING_FUNCTION_MONASTERY_ABBATIAL",
        BUILDING_FUNCTION_MONASTERY_CHAPEL = "BUILDING_FUNCTION_MONASTERY_CHAPEL",
        BUILDING_FUNCTION_RUSTIC_CHURCH = "BUILDING_FUNCTION_RUSTIC_CHURCH",
    },

    BUILDING_FUNCTION_CRAFTING_WORKSHOP = {
        BUILDING_FUNCTION_SCULPTURE_WORKSHOP = "BUILDING_FUNCTION_SCULPTURE_WORKSHOP",
        BUILDING_FUNCTION_STAINED_GLASS_WORKSHOP = "BUILDING_FUNCTION_STAINED_GLASS_WORKSHOP",
    },

    BUILDING_FUNCTION_ENCAMPMENT = {
        BUILDING_FUNCTION_CASTLE_ENCAMPMENT_BOW = "BUILDING_FUNCTION_CASTLE_ENCAMPMENT_BOW",
        BUILDING_FUNCTION_CASTLE_ENCAMPMENT_KEEP = "BUILDING_FUNCTION_CASTLE_ENCAMPMENT_KEEP",
        BUILDING_FUNCTION_CASTLE_ENCAMPMENT_SPEAR = "BUILDING_FUNCTION_CASTLE_ENCAMPMENT_SPEAR",
        BUILDING_FUNCTION_CASTLE_ENCAMPMENT_SWORD = "BUILDING_FUNCTION_CASTLE_ENCAMPMENT_SWORD",
    },

    BUILDING_FUNCTION_FARM = {
        BUILDING_FUNCTION_HOP_FARM = "BUILDING_FUNCTION_HOP_FARM",
        BUILDING_FUNCTION_MONASTERY_VEGETABLE_GARDEN = "BUILDING_FUNCTION_MONASTERY_VEGETABLE_GARDEN",
        BUILDING_FUNCTION_VINEYARD = "BUILDING_FUNCTION_VINEYARD",
        BUILDING_FUNCTION_WHEAT_FARM = "BUILDING_FUNCTION_WHEAT_FARM",
    },

    BUILDING_FUNCTION_FISHING = {
        BUILDING_FUNCTION_FISHING_HUT = "BUILDING_FUNCTION_FISHING_HUT",
    },

    BUILDING_FUNCTION_FORESTER = {
        BUILDING_FUNCTION_FORESTER = "BUILDING_FUNCTION_FORESTER",
    },

    BUILDING_FUNCTION_GREAT_HALL = {
        BUILDING_FUNCTION_GREAT_HALL = "BUILDING_FUNCTION_GREAT_HALL",
    },

    BUILDING_FUNCTION_HEALING_HOUSE = {
        BUILDING_FUNCTION_CASTLE_HEALING_HOUSE = "BUILDING_FUNCTION_CASTLE_HEALING_HOUSE",
    },

    BUILDING_FUNCTION_HOUSE = {
        BUILDING_FUNCTION_CASTLE_BARRACK_HOUSING = "BUILDING_FUNCTION_CASTLE_BARRACK_HOUSING",
        BUILDING_FUNCTION_CASTLE_QUARTERS_HOUSING = "BUILDING_FUNCTION_CASTLE_QUARTERS_HOUSING",
        BUILDING_FUNCTION_HOUSING = "BUILDING_FUNCTION_HOUSING",
        BUILDING_FUNCTION_MONASTERY_DORM_MONKS = "BUILDING_FUNCTION_MONASTERY_DORM_MONKS",
        BUILDING_FUNCTION_MONASTERY_DORM_NUNS = "BUILDING_FUNCTION_MONASTERY_DORM_NUNS",
    },

    BUILDING_FUNCTION_INTERACTIVE_LOCATION = {
        BUILDING_FUNCTION_GUARD_LOCATION = "BUILDING_FUNCTION_GUARD_LOCATION",
    },

    BUILDING_FUNCTION_KITCHEN = {
        BUILDING_FUNCTION_KITCHEN = "BUILDING_FUNCTION_KITCHEN",
    },

    BUILDING_FUNCTION_KNIGHT_STATUE = {
        BUILDING_FUNCTION_COURT_HEROES = "BUILDING_FUNCTION_COURT_HEROES",
    },

    BUILDING_FUNCTION_LIVESTOCK_FARM = {
        BUILDING_FUNCTION_DAIRY_FARM = "BUILDING_FUNCTION_DAIRY_FARM",
        BUILDING_FUNCTION_SHEEP_FARM = "BUILDING_FUNCTION_SHEEP_FARM",
    },

    BUILDING_FUNCTION_LODGING = {
        BUILDING_FUNCTION_CASTLE_BARRACK_LODGING = "BUILDING_FUNCTION_CASTLE_BARRACK_LODGING",
        BUILDING_FUNCTION_CASTLE_QUARTERS_LODGING = "BUILDING_FUNCTION_CASTLE_QUARTERS_LODGING",
        BUILDING_FUNCTION_MONASTERY_HOSPITIUM = "BUILDING_FUNCTION_MONASTERY_HOSPITIUM",
        BUILDING_FUNCTION_TAVERN_INN_LODGE = "BUILDING_FUNCTION_TAVERN_INN_LODGE",
    },

    BUILDING_FUNCTION_MARKET = {
        BUILDING_FUNCTION_CASTLE_MESS_HALL = "BUILDING_FUNCTION_CASTLE_MESS_HALL",
        BUILDING_FUNCTION_CITY_MARKET_TABLE_FOOD = "BUILDING_FUNCTION_CITY_MARKET_TABLE_FOOD",
        BUILDING_FUNCTION_CITY_MARKET_TABLE_GOODS = "BUILDING_FUNCTION_CITY_MARKET_TABLE_GOODS",
        BUILDING_FUNCTION_CITY_MARKET_TABLE_LUXURY = "BUILDING_FUNCTION_CITY_MARKET_TABLE_LUXURY",
        BUILDING_FUNCTION_FOOD_MARKET = "BUILDING_FUNCTION_FOOD_MARKET",
        BUILDING_FUNCTION_GOODS_MARKET = "BUILDING_FUNCTION_GOODS_MARKET",
        BUILDING_FUNCTION_LUXURY_MARKET = "BUILDING_FUNCTION_LUXURY_MARKET",
        BUILDING_FUNCTION_MONASTERY_REFECTORY = "BUILDING_FUNCTION_MONASTERY_REFECTORY",
        BUILDING_FUNCTION_TAVERN_SERVICE_COUNTER = "BUILDING_FUNCTION_TAVERN_SERVICE_COUNTER",
    },

    BUILDING_FUNCTION_MARKET_TENT = {
        BUILDING_FUNCTION_CITY_MARKET_TENT = "BUILDING_FUNCTION_CITY_MARKET_TENT",
        BUILDING_FUNCTION_MARKET_TENT = "BUILDING_FUNCTION_MARKET_TENT",
    },

    BUILDING_FUNCTION_MONASTERY = {
        BUILDING_FUNCTION_MONASTERY = "BUILDING_FUNCTION_MONASTERY",
    },

    BUILDING_FUNCTION_MUSICAL_PART = {
        BUILDING_FUNCTION_BELFRY_TOP = "BUILDING_FUNCTION_BELFRY_TOP",
        BUILDING_FUNCTION_LARGE_BELL = "BUILDING_FUNCTION_LARGE_BELL",
        BUILDING_FUNCTION_SMALL_BELL = "BUILDING_FUNCTION_SMALL_BELL",
    },

    BUILDING_FUNCTION_PATROL_WORKPLACE = {
        BUILDING_FUNCTION_WATCHPOST_PATROL = "BUILDING_FUNCTION_WATCHPOST_PATROL",
    },

    BUILDING_FUNCTION_PUBLIC_LOUNGE = {
        BUILDING_FUNCTION_TAVERN_PUBLIC_LOUNGE = "BUILDING_FUNCTION_TAVERN_PUBLIC_LOUNGE",
    },

    BUILDING_FUNCTION_PUBLIC_LOUNGE_ROOM = {
        BUILDING_FUNCTION_PUBLIC_LOUNGE_ROOM = "BUILDING_FUNCTION_PUBLIC_LOUNGE_ROOM",
    },

    BUILDING_FUNCTION_QUARRY = {
        BUILDING_FUNCTION_QUARRY_GOLD = "BUILDING_FUNCTION_QUARRY_GOLD",
        BUILDING_FUNCTION_QUARRY_IRON = "BUILDING_FUNCTION_QUARRY_IRON",
        BUILDING_FUNCTION_QUARRY_MARBLE = "BUILDING_FUNCTION_QUARRY_MARBLE",
        BUILDING_FUNCTION_QUARRY_QUARTZ = "BUILDING_FUNCTION_QUARRY_QUARTZ",
        BUILDING_FUNCTION_QUARRY_STONE = "BUILDING_FUNCTION_QUARRY_STONE",
    },

    BUILDING_FUNCTION_RESOURCE_DEPOT = {
        BUILDING_FUNCTION_MONASTERY_GARDEN_STORAGE = "BUILDING_FUNCTION_MONASTERY_GARDEN_STORAGE",
        BUILDING_FUNCTION_QUARRY_STORAGE_IMPROVEMENT_SMALL = "BUILDING_FUNCTION_QUARRY_STORAGE_IMPROVEMENT_SMALL",
        BUILDING_FUNCTION_STONEMASON_STORAGE_BASE = "BUILDING_FUNCTION_STONEMASON_STORAGE_BASE",
        BUILDING_FUNCTION_STONEMASON_STORAGE_IMPROVEMENT_LARGE = "BUILDING_FUNCTION_STONEMASON_STORAGE_IMPROVEMENT_LARGE",
        BUILDING_FUNCTION_VINEYARD_STORAGE_IMPROVEMENT = "BUILDING_FUNCTION_VINEYARD_STORAGE_IMPROVEMENT",
        BUILDING_FUNCTION_WHEATFARM_STORAGE_BASE = "BUILDING_FUNCTION_WHEATFARM_STORAGE_BASE",
        BUILDING_FUNCTION_WHEATFARM_STORAGE_IMPROVEMENT_LARGE = "BUILDING_FUNCTION_WHEATFARM_STORAGE_IMPROVEMENT_LARGE",
        BUILDING_FUNCTION_WHEATFARM_STORAGE_IMPROVEMENT_SMALL = "BUILDING_FUNCTION_WHEATFARM_STORAGE_IMPROVEMENT_SMALL",
        BUILDING_FUNCTION_WOODCUTTER_STORAGE_BASE = "BUILDING_FUNCTION_WOODCUTTER_STORAGE_BASE",
        BUILDING_FUNCTION_WOODCUTTER_STORAGE_IMPROVEMENT_LARGE = "BUILDING_FUNCTION_WOODCUTTER_STORAGE_IMPROVEMENT_LARGE",
        BUILDING_FUNCTION_WOODCUTTER_STORAGE_IMPROVEMENT_SMALL = "BUILDING_FUNCTION_WOODCUTTER_STORAGE_IMPROVEMENT_SMALL",
    },

    BUILDING_FUNCTION_RESOURCE_GENERATOR = {
        BUILDING_FUNCTION_WELL = "BUILDING_FUNCTION_WELL",
        DEFAULT_FAITH_GENERATOR = "DEFAULT_FAITH_GENERATOR",
    },

    BUILDING_FUNCTION_TAX_OFFICE = {
        BUILDING_FUNCTION_TAX_OFFICE = "BUILDING_FUNCTION_TAX_OFFICE",
    },

    BUILDING_FUNCTION_TRAINING_SITE = {
        BUILDING_FUNCTION_TRAINING_SITE = "BUILDING_FUNCTION_TRAINING_SITE",
    },

    BUILDING_FUNCTION_TREASURY = {
        BUILDING_FUNCTION_TREASURY = "BUILDING_FUNCTION_TREASURY",
    },

    BUILDING_FUNCTION_UNIQUE_RESOURCE_DEPOT = {
        BUILDING_FUNCTION_QUARRY_STORAGE = "BUILDING_FUNCTION_QUARRY_STORAGE",
    },

    BUILDING_FUNCTION_VILLAGE_CENTER = {
        BUILDING_FUNCTION_VILLAGE_CENTER = "BUILDING_FUNCTION_VILLAGE_CENTER",
    },

    BUILDING_FUNCTION_WAREHOUSE = {
        BUILDING_FUNCTION_CASTLE_ARMORY = "BUILDING_FUNCTION_CASTLE_ARMORY",
        BUILDING_FUNCTION_CITY_MARKET_STORAGE = "BUILDING_FUNCTION_CITY_MARKET_STORAGE",
        BUILDING_FUNCTION_GRANARY = "BUILDING_FUNCTION_GRANARY",
        BUILDING_FUNCTION_MONASTERY_STORAGE = "BUILDING_FUNCTION_MONASTERY_STORAGE",
        BUILDING_FUNCTION_WAREHOUSE = "BUILDING_FUNCTION_WAREHOUSE",
    },

    BUILDING_FUNCTION_WATCHPOST = {
        BUILDING_FUNCTION_WATCHPOST = "BUILDING_FUNCTION_WATCHPOST",
    },

    BUILDING_FUNCTION_WORKER_CAPACITY_EXTENDER = {
        BUILDING_FUNCTION_CASTLE_ENCAMPMENT_EXTENDER = "BUILDING_FUNCTION_CASTLE_ENCAMPMENT_EXTENDER",
        BUILDING_FUNCTION_MONASTERY_GARDEN_PLANTER = "BUILDING_FUNCTION_MONASTERY_GARDEN_PLANTER",
        BUILDING_FUNCTION_STONEMASON_WORKER_IMPROVEMENT_LARGE = "BUILDING_FUNCTION_STONEMASON_WORKER_IMPROVEMENT_LARGE",
        BUILDING_FUNCTION_STONEMASON_WORKER_IMPROVEMENT_SMALL = "BUILDING_FUNCTION_STONEMASON_WORKER_IMPROVEMENT_SMALL",
        BUILDING_FUNCTION_VINEYARD_WORKER_IMPROVEMENT = "BUILDING_FUNCTION_VINEYARD_WORKER_IMPROVEMENT",
        BUILDING_FUNCTION_WHEATFARM_WORKER_IMPROVEMENT_LARGE = "BUILDING_FUNCTION_WHEATFARM_WORKER_IMPROVEMENT_LARGE",
        BUILDING_FUNCTION_WOODCUTTER_WORKER_IMPROVEMENT_LARGE = "BUILDING_FUNCTION_WOODCUTTER_WORKER_IMPROVEMENT_LARGE",
        BUILDING_FUNCTION_WOODCUTTER_WORKER_IMPROVEMENT_SMALL = "BUILDING_FUNCTION_WOODCUTTER_WORKER_IMPROVEMENT_SMALL",
    },

    BUILDING_FUNCTION_WORKPLACE = {
        BUILDING_FUNCTION_BAKERY = "BUILDING_FUNCTION_BAKERY",
        BUILDING_FUNCTION_BLACKSMITH = "BUILDING_FUNCTION_BLACKSMITH",
        BUILDING_FUNCTION_BOWYER_RECIPE_A = "BUILDING_FUNCTION_BOWYER_RECIPE_A",
        BUILDING_FUNCTION_BOWYER_RECIPE_B = "BUILDING_FUNCTION_BOWYER_RECIPE_B",
        BUILDING_FUNCTION_BREWERY = "BUILDING_FUNCTION_BREWERY",
        BUILDING_FUNCTION_BUTCHER = "BUILDING_FUNCTION_BUTCHER",
        BUILDING_FUNCTION_CANDLE_WORKSHOP = "BUILDING_FUNCTION_CANDLE_WORKSHOP",
        BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_A = "BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_A",
        BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_B = "BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_B",
        BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_C = "BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_C",
        BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_D = "BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_D",
        BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_E = "BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_E",
        BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_F = "BUILDING_FUNCTION_CASTLE_PROVISIONER_RECIPE_F",
        BUILDING_FUNCTION_CHEESE_MAKER = "BUILDING_FUNCTION_CHEESE_MAKER",
        BUILDING_FUNCTION_COAL_HUT = "BUILDING_FUNCTION_COAL_HUT",
        BUILDING_FUNCTION_COMMON_WARES_WORKSHOP = "BUILDING_FUNCTION_COMMON_WARES_WORKSHOP",
        BUILDING_FUNCTION_COOPERAGE = "BUILDING_FUNCTION_COOPERAGE",
        BUILDING_FUNCTION_GATHERING_HUT = "BUILDING_FUNCTION_GATHERING_HUT",
        BUILDING_FUNCTION_GLASS_SMELTER = "BUILDING_FUNCTION_GLASS_SMELTER",
        BUILDING_FUNCTION_GOLD_SMELTER = "BUILDING_FUNCTION_GOLD_SMELTER",
        BUILDING_FUNCTION_HUNTERS_HUT = "BUILDING_FUNCTION_HUNTERS_HUT",
        BUILDING_FUNCTION_INN_BREWERY = "BUILDING_FUNCTION_INN_BREWERY",
        BUILDING_FUNCTION_IRON_MINE = "BUILDING_FUNCTION_IRON_MINE",
        BUILDING_FUNCTION_IRON_SMELTER = "BUILDING_FUNCTION_IRON_SMELTER",
        BUILDING_FUNCTION_JEWELER_WORKSHOP = "BUILDING_FUNCTION_JEWELER_WORKSHOP",
        BUILDING_FUNCTION_MONASTERY_BEEKEEPING = "BUILDING_FUNCTION_MONASTERY_BEEKEEPING",
        BUILDING_FUNCTION_MONASTERY_BERRY_GARDEN = "BUILDING_FUNCTION_MONASTERY_BERRY_GARDEN",
        BUILDING_FUNCTION_MONASTERY_HERB_GARDEN = "BUILDING_FUNCTION_MONASTERY_HERB_GARDEN",
        BUILDING_FUNCTION_MONASTERY_KITCHEN_RECIPE_A = "BUILDING_FUNCTION_MONASTERY_KITCHEN_RECIPE_A",
        BUILDING_FUNCTION_MONASTERY_KITCHEN_RECIPE_B = "BUILDING_FUNCTION_MONASTERY_KITCHEN_RECIPE_B",
        BUILDING_FUNCTION_MONASTERY_KITCHEN_RECIPE_C = "BUILDING_FUNCTION_MONASTERY_KITCHEN_RECIPE_C",
        BUILDING_FUNCTION_MONASTERY_KITCHEN_RECIPE_D = "BUILDING_FUNCTION_MONASTERY_KITCHEN_RECIPE_D",
        BUILDING_FUNCTION_MONASTERY_SCRIPTORIUM = "BUILDING_FUNCTION_MONASTERY_SCRIPTORIUM",
        BUILDING_FUNCTION_MONASTERY_WINERY = "BUILDING_FUNCTION_MONASTERY_WINERY",
        BUILDING_FUNCTION_PAVIOR_YARD = "BUILDING_FUNCTION_PAVIOR_YARD",
        BUILDING_FUNCTION_SAWMILL = "BUILDING_FUNCTION_SAWMILL",
        BUILDING_FUNCTION_SPEARMAKER_RECIPE_A = "BUILDING_FUNCTION_SPEARMAKER_RECIPE_A",
        BUILDING_FUNCTION_SPEARMAKER_RECIPE_B = "BUILDING_FUNCTION_SPEARMAKER_RECIPE_B",
        BUILDING_FUNCTION_STONECUTTER_CAMP = "BUILDING_FUNCTION_STONECUTTER_CAMP",
        BUILDING_FUNCTION_STONEMASON_HUT = "BUILDING_FUNCTION_STONEMASON_HUT",
        BUILDING_FUNCTION_SWORDSMITH_RECIPE_A = "BUILDING_FUNCTION_SWORDSMITH_RECIPE_A",
        BUILDING_FUNCTION_SWORDSMITH_RECIPE_B = "BUILDING_FUNCTION_SWORDSMITH_RECIPE_B",
        BUILDING_FUNCTION_TAILOR_WORKSHOP = "BUILDING_FUNCTION_TAILOR_WORKSHOP",
        BUILDING_FUNCTION_WEAVER_HUT = "BUILDING_FUNCTION_WEAVER_HUT",
        BUILDING_FUNCTION_WINDMILL = "BUILDING_FUNCTION_WINDMILL",
        BUILDING_FUNCTION_WOODCUTTER = "BUILDING_FUNCTION_WOODCUTTER",
    },

    BUILDING_FUNCTION_WORKPLACE_GUARD = {
        BUILDING_FUNCTION_WATCHPOST_GUARD = "BUILDING_FUNCTION_WATCHPOST_GUARD",
    },
}