---@meta

---
---EXECUTE_ACTION_LIST_MANDATE_TYPE
---Lua enum for mandate types used in execute action lists within the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/execute_action_list_mandate_type)
---
---@enum EXECUTE_ACTION_LIST_MANDATE_TYPE_ASSET
EXECUTE_ACTION_LIST_MANDATE_TYPE = {
    MANDATE_IMMIGRATION_CLERGY_FEMALE = "MANDATE_IMMIGRATION_CLERGY_FEMALE",
    MANDATE_IMMIGRATION_CLERGY_MALE = "MANDATE_IMMIGRATION_CLERGY_MALE",
    MANDATE_IMMIGRATION_KINGDOM = "MANDATE_IMMIGRATION_KINGDOM",
    MANDATE_IMMIGRATION_LABOUR = "MANDATE_IMMIGRATION_LABOUR",
    MANDATE_REMOVE_MONASTIC = "MANDATE_REMOVE_MONASTIC",
    MANDATE_REMOVE_VILLAGER = "MANDATE_REMOVE_VILLAGER",
    MANDATE_SUMMON_KINGDOM_CAMPAIGN_INTRO = "MANDATE_SUMMON_KINGDOM_CAMPAIGN_INTRO",
    MANDATE_SUMMON_KINGDOM_HOSTING_INTRO = "MANDATE_SUMMON_KINGDOM_HOSTING_INTRO",
    MANDATE_SUMMON_KINGDOM_HOSTING_KING_INTRO = "MANDATE_SUMMON_KINGDOM_HOSTING_KING_INTRO",
    MANDATE_SUMMON_KINGDOM_HOSTING_PAUSE = "MANDATE_SUMMON_KINGDOM_HOSTING_PAUSE",
    MANDATE_SUMMON_KINGDOM_HOSTING_RESTART = "MANDATE_SUMMON_KINGDOM_HOSTING_RESTART",
    MANDATE_SUMMON_LABOUR_ASPIRATION_STEP2 = "MANDATE_SUMMON_LABOUR_ASPIRATION_STEP2",
    MANDATE_SUMMON_LABOUR_HOSTING_SENESCHAL_INTRO = "MANDATE_SUMMON_LABOUR_HOSTING_SENESCHAL_INTRO",
}