---@meta

---
---GUEST
---Lua enum for guest asset types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/guest)
---
---@enum GUEST_ASSET
GUEST = {
    GUEST_ADVANCEDONBOARDING_CLERGYINFLUENCE_PRIEST = "GUEST_ADVANCEDONBOARDING_CLERGYINFLUENCE_PRIEST",
    GUEST_ADVANCEDONBOARDING_LABOURINFLUENCE_VILLAGER = "GUEST_ADVANCEDONBOARDING_LABOURINFLUENCE_VILLAGER",
    GUEST_ADVANCEDONBOARDING_VISITHOSPITIUM_STEWARD = "GUEST_ADVANCEDONBOARDING_VISITHOSPITIUM_STEWARD",
    GUEST_HOSPITIUM_HOSTING_LOW = "GUEST_HOSPITIUM_HOSTING_LOW",
    GUEST_HOSPITIUM_HOSTING_MONK = "GUEST_HOSPITIUM_HOSTING_MONK",
    GUEST_HOSPITIUM_HOSTING_NUN = "GUEST_HOSPITIUM_HOSTING_NUN",
    GUEST_HOSPITIUM_HOSTING_PILGRIM_HIGH = "GUEST_HOSPITIUM_HOSTING_PILGRIM_HIGH",
    GUEST_HOSPITIUM_HOSTING_RECRUIT = "GUEST_HOSPITIUM_HOSTING_RECRUIT",
    GUEST_HOSPITIUM_HOSTING_SOLDIER = "GUEST_HOSPITIUM_HOSTING_SOLDIER",
    GUEST_KINGDOM_HOSTING_KNIGHT = "GUEST_KINGDOM_HOSTING_KNIGHT",
    GUEST_KINGDOM_HOSTING_MILITIAMAN = "GUEST_KINGDOM_HOSTING_MILITIAMAN",
    GUEST_KINGDOM_HOSTING_SOLDIER = "GUEST_KINGDOM_HOSTING_SOLDIER",
    GUEST_KINGDOM_KING_HOSTING_KING = "GUEST_KINGDOM_KING_HOSTING_KING",
    GUEST_KINGDOM_KING_HOSTING_KING_RETINUE = "GUEST_KINGDOM_KING_HOSTING_KING_RETINUE",
    GUEST_KINGDOM_KING_HOSTING_KNIGHT = "GUEST_KINGDOM_KING_HOSTING_KNIGHT",
    GUEST_KINGDOM_KING_HOSTING_MILITIAMAN = "GUEST_KINGDOM_KING_HOSTING_MILITIAMAN",
    GUEST_KINGDOM_KING_HOSTING_SOLDIER = "GUEST_KINGDOM_KING_HOSTING_SOLDIER",
    GUEST_LABOURFAIR_FOOD_HIGH = "GUEST_LABOURFAIR_FOOD_HIGH",
    GUEST_LABOURFAIR_FOOD_LOW = "GUEST_LABOURFAIR_FOOD_LOW",
    GUEST_LABOURFAIR_FOOD_MEDIUM = "GUEST_LABOURFAIR_FOOD_MEDIUM",
    GUEST_LABOURWELCOME = "GUEST_LABOURWELCOME",
    GUEST_LABOUR_LODGING_TRAVELLER_HIGH = "GUEST_LABOUR_LODGING_TRAVELLER_HIGH",
    GUEST_LABOUR_LODGING_TRAVELLER_LOW = "GUEST_LABOUR_LODGING_TRAVELLER_LOW",
    GUEST_LABOUR_LODGING_TRAVELLER_SOLDIER = "GUEST_LABOUR_LODGING_TRAVELLER_SOLDIER",
    GUEST_LABOUR_SENESCHAL_HOSTING_ELDER = "GUEST_LABOUR_SENESCHAL_HOSTING_ELDER",
    GUEST_LABOUR_SENESCHAL_HOSTING_GUARD = "GUEST_LABOUR_SENESCHAL_HOSTING_GUARD",
    GUEST_LABOUR_SENESCHAL_HOSTING_SENESCHAL = "GUEST_LABOUR_SENESCHAL_HOSTING_SENESCHAL",
    GUEST_MONASTERYBREAD_STEWARD = "GUEST_MONASTERYBREAD_STEWARD",
    GUEST_MONASTERYHOSTING_MONK = "GUEST_MONASTERYHOSTING_MONK",
    GUEST_MONASTERYHOSTING_MYDDLE_PEOPLE = "GUEST_MONASTERYHOSTING_MYDDLE_PEOPLE",
    GUEST_MONASTERYTRADE_ABBESS_ENVOY = "GUEST_MONASTERYTRADE_ABBESS_ENVOY",
    GUEST_MONASTERYTRADE_MERCHANT = "GUEST_MONASTERYTRADE_MERCHANT",
    GUEST_MONASTERY_ABBESS_HOSTING_ABBESS = "GUEST_MONASTERY_ABBESS_HOSTING_ABBESS",
    GUEST_MONASTERY_ABBESS_HOSTING_ABBESS_RETINUE = "GUEST_MONASTERY_ABBESS_HOSTING_ABBESS_RETINUE",
    GUEST_MONASTERY_ABBESS_HOSTING_MERCHANT = "GUEST_MONASTERY_ABBESS_HOSTING_MERCHANT",
    GUEST_MONASTERY_ABBESS_HOSTING_PILGRIM = "GUEST_MONASTERY_ABBESS_HOSTING_PILGRIM",
    GUEST_MONASTERY_ABBESS_HOSTING_PRIO = "GUEST_MONASTERY_ABBESS_HOSTING_PRIO",
    GUEST_MONASTERY_ABBESS_HOSTING_SOLDIER = "GUEST_MONASTERY_ABBESS_HOSTING_SOLDIER",
    GUEST_MONASTERY_WINE_GUARD = "GUEST_MONASTERY_WINE_GUARD",
    GUEST_MONASTERY_WINE_STEWARD = "GUEST_MONASTERY_WINE_STEWARD",
}