---@meta

---
---Lua enum for guest requirement asset types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/guest_requirement)
---
---@enum GUEST_REQUIREMENT_ASSET
GUEST_REQUIREMENT_ASSET = {
    GUEST_REQUIREMENT_CASTLE_BARRACKS = "GUEST_REQUIREMENT_CASTLE_BARRACKS",
    GUEST_REQUIREMENT_CASTLE_QUARTERS = "GUEST_REQUIREMENT_CASTLE_QUARTERS",
    GUEST_REQUIREMENT_COMBATANT_HEALING = "GUEST_REQUIREMENT_COMBATANT_HEALING",
    GUEST_REQUIREMENT_ENTERTAINMENT = "GUEST_REQUIREMENT_ENTERTAINMENT",
    GUEST_REQUIREMENT_FOOD = "GUEST_REQUIREMENT_FOOD",
    GUEST_REQUIREMENT_FOOD_MONASTIC = "GUEST_REQUIREMENT_FOOD_MONASTIC",
    GUEST_REQUIREMENT_FOOD_REFINED = "GUEST_REQUIREMENT_FOOD_REFINED",
    GUEST_REQUIREMENT_FOOD_REFINED_HIGH = "GUEST_REQUIREMENT_FOOD_REFINED_HIGH",
    GUEST_REQUIREMENT_GOODS = "GUEST_REQUIREMENT_GOODS",
    GUEST_REQUIREMENT_GOODS_HIGH = "GUEST_REQUIREMENT_GOODS_HIGH",
    GUEST_REQUIREMENT_LUXURY = "GUEST_REQUIREMENT_LUXURY",
    GUEST_REQUIREMENT_LUXURY_HIGH = "GUEST_REQUIREMENT_LUXURY_HIGH",
    GUEST_REQUIREMENT_MONASTERY_HOSPITIUM = "GUEST_REQUIREMENT_MONASTERY_HOSPITIUM",
    GUEST_REQUIREMENT_SERVICE = "GUEST_REQUIREMENT_SERVICE",
    GUEST_REQUIREMENT_SERVICE_HIGH = "GUEST_REQUIREMENT_SERVICE_HIGH",
    GUEST_REQUIREMENT_TAVERN_INN = "GUEST_REQUIREMENT_TAVERN_INN",
    GUEST_REQUIREMENT_TRAINING = "GUEST_REQUIREMENT_TRAINING",
    GUEST_REQUIREMENT_VISIT_ABBATIAL = "GUEST_REQUIREMENT_VISIT_ABBATIAL",
    GUEST_REQUIREMENT_VISIT_APIARY = "GUEST_REQUIREMENT_VISIT_APIARY",
    GUEST_REQUIREMENT_VISIT_BUILDER = "GUEST_REQUIREMENT_VISIT_BUILDER",
    GUEST_REQUIREMENT_VISIT_CLOISTER = "GUEST_REQUIREMENT_VISIT_CLOISTER",
    GUEST_REQUIREMENT_VISIT_GREAT_HALL = "GUEST_REQUIREMENT_VISIT_GREAT_HALL",
    GUEST_REQUIREMENT_VISIT_MONASTERY_KITCHEN = "GUEST_REQUIREMENT_VISIT_MONASTERY_KITCHEN",
    GUEST_REQUIREMENT_VISIT_SCRIPTORIUM = "GUEST_REQUIREMENT_VISIT_SCRIPTORIUM",
    GUEST_REQUIREMENT_VISIT_VINEYARD_HIGH = "GUEST_REQUIREMENT_VISIT_VINEYARD_HIGH",
    GUEST_REQUIREMENT_VISIT_WINERY = "GUEST_REQUIREMENT_VISIT_WINERY",
    GUEST_REQUIREMENT_VISIT_WINERY_HIGH = "GUEST_REQUIREMENT_VISIT_WINERY_HIGH",
    GUEST_REQUIREMENT_WATER = "GUEST_REQUIREMENT_WATER",
}