---@meta

---
---Enumeration of happiness factor asset constants.
---Lua enum for asset/resource types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/happiness_factor)
---
---@enum HAPPINESS_FACTOR_ASSET
HAPPINESS_FACTOR = {
    HAPPINESS_FACTOR_ASPIRATION_LABOUR = "HAPPINESS_FACTOR_ASPIRATION_LABOUR",
    HAPPINESS_FACTOR_BASE = "HAPPINESS_FACTOR_BASE",
    HAPPINESS_FACTOR_FORCE_HOUSE_SWITCH = "HAPPINESS_FACTOR_FORCE_HOUSE_SWITCH",
    HAPPINESS_FACTOR_KINGDOM_KING_HOSTING_BONUS = "HAPPINESS_FACTOR_KINGDOM_KING_HOSTING_BONUS",
    HAPPINESS_FACTOR_KINGDOM_KING_HOSTING_MALUS = "HAPPINESS_FACTOR_KINGDOM_KING_HOSTING_MALUS",
    HAPPINESS_FACTOR_LABOURFAIR_GLOOMFAIR = "HAPPINESS_FACTOR_LABOURFAIR_GLOOMFAIR",
    HAPPINESS_FACTOR_LABOURFAIR_HAPPYGUEST = "HAPPINESS_FACTOR_LABOURFAIR_HAPPYGUEST",
    HAPPINESS_FACTOR_LABOURFAIR_MERRYFAIR = "HAPPINESS_FACTOR_LABOURFAIR_MERRYFAIR",
    HAPPINESS_FACTOR_LABOURFAIR_UNHAPPYGUEST = "HAPPINESS_FACTOR_LABOURFAIR_UNHAPPYGUEST",
    HAPPINESS_FACTOR_LABOUR_SENESCHAL_HOSTING_BONUS = "HAPPINESS_FACTOR_LABOUR_SENESCHAL_HOSTING_BONUS",
    HAPPINESS_FACTOR_LABOUR_SENESCHAL_HOSTING_MALUS = "HAPPINESS_FACTOR_LABOUR_SENESCHAL_HOSTING_MALUS",
    HAPPINESS_FACTOR_LACK_ENTERTAINMENT = "HAPPINESS_FACTOR_LACK_ENTERTAINMENT",
    HAPPINESS_FACTOR_LACK_FOOD = "HAPPINESS_FACTOR_LACK_FOOD",
    HAPPINESS_FACTOR_LACK_GOODS = "HAPPINESS_FACTOR_LACK_GOODS",
    HAPPINESS_FACTOR_LACK_HOUSING = "HAPPINESS_FACTOR_LACK_HOUSING",
    HAPPINESS_FACTOR_LACK_LUXURY = "HAPPINESS_FACTOR_LACK_LUXURY",
    HAPPINESS_FACTOR_LACK_SERVICES = "HAPPINESS_FACTOR_LACK_SERVICES",
    HAPPINESS_FACTOR_LACK_VISIT = "HAPPINESS_FACTOR_LACK_VISIT",
    HAPPINESS_FACTOR_LACK_VISIT_SILENT = "HAPPINESS_FACTOR_LACK_VISIT_SILENT",
    HAPPINESS_FACTOR_LACK_WATER = "HAPPINESS_FACTOR_LACK_WATER",
    HAPPINESS_FACTOR_LEVY = "HAPPINESS_FACTOR_LEVY",
    HAPPINESS_FACTOR_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY = "HAPPINESS_FACTOR_MONASTERYHOSTING_WANDERINGMONKS_DELIVERY",
    HAPPINESS_FACTOR_MONASTERYTRADE_GUEST_BONUS = "HAPPINESS_FACTOR_MONASTERYTRADE_GUEST_BONUS",
    HAPPINESS_FACTOR_MONASTERYTRADE_GUEST_MALUS = "HAPPINESS_FACTOR_MONASTERYTRADE_GUEST_MALUS",
    HAPPINESS_FACTOR_MONASTERY_ABBESS_HOSTING_BONUS = "HAPPINESS_FACTOR_MONASTERY_ABBESS_HOSTING_BONUS",
    HAPPINESS_FACTOR_MONASTERY_ABBESS_HOSTING_MALUS = "HAPPINESS_FACTOR_MONASTERY_ABBESS_HOSTING_MALUS",
    HAPPINESS_FACTOR_TAVERN_MEAL = "HAPPINESS_FACTOR_TAVERN_MEAL",
    HAPPINESS_FACTOR_TOWNTALE_GOODTALE = "HAPPINESS_FACTOR_TOWNTALE_GOODTALE",
    TAXATION_HAPPINESS_FACTOR_0 = "TAXATION_HAPPINESS_FACTOR_0",
    TAXATION_HAPPINESS_FACTOR_1 = "TAXATION_HAPPINESS_FACTOR_1",
    TAXATION_HAPPINESS_FACTOR_2 = "TAXATION_HAPPINESS_FACTOR_2",
    TAXATION_HAPPINESS_FACTOR_3 = "TAXATION_HAPPINESS_FACTOR_3",
    TAXATION_HAPPINESS_FACTOR_4 = "TAXATION_HAPPINESS_FACTOR_4",
    TAXATION_HAPPINESS_FACTOR_5 = "TAXATION_HAPPINESS_FACTOR_5",
    TAXATION_HAPPINESS_FACTOR_6 = "TAXATION_HAPPINESS_FACTOR_6",
}