---@meta

---
---PARTICLE_SYSTEM enum
---Lua enum for particle system asset types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/particle_system)
---
---@enum PARTICLE_SYSTEM_ASSET
PARTICLE_SYSTEM = {
    PARTICLE_SYSTEM_BEEKEEPER_BEES = "PARTICLE_SYSTEM_BEEKEEPER_BEES",
    PARTICLE_SYSTEM_BLACKSMITH_GRIND = "PARTICLE_SYSTEM_BLACKSMITH_GRIND",
    PARTICLE_SYSTEM_BLACKSMITH_ROCK = "PARTICLE_SYSTEM_BLACKSMITH_ROCK",
    PARTICLE_SYSTEM_BLACKSMITH_SMOKE = "PARTICLE_SYSTEM_BLACKSMITH_SMOKE",
    PARTICLE_SYSTEM_BUTCHER_SMOKE = "PARTICLE_SYSTEM_BUTCHER_SMOKE",
    PARTICLE_SYSTEM_HOUSING_SMOKE = "PARTICLE_SYSTEM_HOUSING_SMOKE",
    PARTICLE_SYSTEM_SAWMILL_SMOKE = "PARTICLE_SYSTEM_SAWMILL_SMOKE",
    PARTICLE_SYSTEM_SAWMILL_SPARK = "PARTICLE_SYSTEM_SAWMILL_SPARK",
    PARTICLE_SYSTEM_STONECUTTER_ROCK = "PARTICLE_SYSTEM_STONECUTTER_ROCK",
    PARTICLE_SYSTEM_STONECUTTER_SMOKE = "PARTICLE_SYSTEM_STONECUTTER_SMOKE",
}