---@meta

---
---PRIVILEGE
---Lua enum for privilege asset types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/privilege)
---
---@enum PRIVILEGE_ASSET
PRIVILEGE = {
    PRIV_CLERGY_GOOD_NEIGHBOR = "PRIV_CLERGY_GOOD_NEIGHBOR",
    PRIV_CLERGY_PARISH_GRANT = "PRIV_CLERGY_PARISH_GRANT",
    PRIV_CLERGY_PIOUS_FASTING = "PRIV_CLERGY_PIOUS_FASTING",
    PRIV_CLERGY_SEAL_OF_PRESTIGE = "PRIV_CLERGY_SEAL_OF_PRESTIGE",
    PRIV_CLERGY_TITHE_TAXES = "PRIV_CLERGY_TITHE_TAXES",
    PRIV_CLERGY_TRADE_COVENANT = "PRIV_CLERGY_TRADE_COVENANT",
    PRIV_KINGDOM_ECONOMIC_ALLIANCE = "PRIV_KINGDOM_ECONOMIC_ALLIANCE",
    PRIV_KINGDOM_INHERITED_LAND = "PRIV_KINGDOM_INHERITED_LAND",
    PRIV_KINGDOM_KINGS_ACCOLADE = "PRIV_KINGDOM_KINGS_ACCOLADE",
    PRIV_KINGDOM_PROTECTION_TAXATION = "PRIV_KINGDOM_PROTECTION_TAXATION",
    PRIV_KINGDOM_STATELY_CONTRIBUTION = "PRIV_KINGDOM_STATELY_CONTRIBUTION",
    PRIV_LABOUR_ADDITIONAL_TAXATION = "PRIV_LABOUR_ADDITIONAL_TAXATION",
    PRIV_LABOUR_CIVIC_CHORES = "PRIV_LABOUR_CIVIC_CHORES",
    PRIV_LABOUR_DUTIFUL_PAYERS = "PRIV_LABOUR_DUTIFUL_PAYERS",
    PRIV_LABOUR_FAIR_REPUTATION = "PRIV_LABOUR_FAIR_REPUTATION",
    PRIV_LABOUR_FAMILY_BUSINESS = "PRIV_LABOUR_FAMILY_BUSINESS",
    PRIV_LABOUR_MERCHANDISE_TAXES = "PRIV_LABOUR_MERCHANDISE_TAXES",
    PRIV_LABOUR_MERCHANT_LEAGUE = "PRIV_LABOUR_MERCHANT_LEAGUE",
}