---@meta

---
---PROGRESS_TIER_DATA
---Lua enum for progress tier data asset types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/progress_tier_data)
---
---@enum PROGRESS_TIER_DATA_ASSET
PROGRESS_TIER_DATA = {
    PROGRESS_TIER_CLERGY_T1 = "PROGRESS_TIER_CLERGY_T1",
    PROGRESS_TIER_CLERGY_T2 = "PROGRESS_TIER_CLERGY_T2",
    PROGRESS_TIER_CLERGY_T3 = "PROGRESS_TIER_CLERGY_T3",
    PROGRESS_TIER_CLERGY_T4 = "PROGRESS_TIER_CLERGY_T4",
    PROGRESS_TIER_CLERGY_T5 = "PROGRESS_TIER_CLERGY_T5",
    PROGRESS_TIER_COMMON_T1 = "PROGRESS_TIER_COMMON_T1",
    PROGRESS_TIER_COMMON_T2 = "PROGRESS_TIER_COMMON_T2",
    PROGRESS_TIER_COMMON_T3 = "PROGRESS_TIER_COMMON_T3",
    PROGRESS_TIER_COMMON_T4 = "PROGRESS_TIER_COMMON_T4",
    PROGRESS_TIER_COMMON_T5 = "PROGRESS_TIER_COMMON_T5",
    PROGRESS_TIER_KINGDOM_T1 = "PROGRESS_TIER_KINGDOM_T1",
    PROGRESS_TIER_KINGDOM_T2 = "PROGRESS_TIER_KINGDOM_T2",
    PROGRESS_TIER_KINGDOM_T3 = "PROGRESS_TIER_KINGDOM_T3",
    PROGRESS_TIER_KINGDOM_T4 = "PROGRESS_TIER_KINGDOM_T4",
    PROGRESS_TIER_KINGDOM_T5 = "PROGRESS_TIER_KINGDOM_T5",
    PROGRESS_TIER_LABOUR_T1 = "PROGRESS_TIER_LABOUR_T1",
    PROGRESS_TIER_LABOUR_T2 = "PROGRESS_TIER_LABOUR_T2",
    PROGRESS_TIER_LABOUR_T3 = "PROGRESS_TIER_LABOUR_T3",
    PROGRESS_TIER_LABOUR_T4 = "PROGRESS_TIER_LABOUR_T4",
    PROGRESS_TIER_LABOUR_T5 = "PROGRESS_TIER_LABOUR_T5",
}