---@meta

---
---QUEST_MILITARY_HOSTING_MISSION
---Lua enum for military hosting quest identifiers used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/quest_military_hosting_mission)
---
---@enum QUEST_MILITARY_HOSTING_MISSION_ASSET
QUEST_MILITARY_HOSTING_MISSION = {
    QUEST_KINGDOM_HOSTING_KNIGHT_T1 = "QUEST_KINGDOM_HOSTING_KNIGHT_T1",
    QUEST_KINGDOM_HOSTING_KNIGHT_T2 = "QUEST_KINGDOM_HOSTING_KNIGHT_T2",
    QUEST_KINGDOM_HOSTING_KNIGHT_T3 = "QUEST_KINGDOM_HOSTING_KNIGHT_T3",
    QUEST_KINGDOM_HOSTING_KNIGHT_T4 = "QUEST_KINGDOM_HOSTING_KNIGHT_T4",
    QUEST_KINGDOM_HOSTING_KNIGHT_T5 = "QUEST_KINGDOM_HOSTING_KNIGHT_T5",
    QUEST_KINGDOM_HOSTING_MILITIAMAN_T1 = "QUEST_KINGDOM_HOSTING_MILITIAMAN_T1",
    QUEST_KINGDOM_HOSTING_MILITIAMAN_T2 = "QUEST_KINGDOM_HOSTING_MILITIAMAN_T2",
    QUEST_KINGDOM_HOSTING_MILITIAMAN_T3 = "QUEST_KINGDOM_HOSTING_MILITIAMAN_T3",
    QUEST_KINGDOM_HOSTING_MILITIAMAN_T4 = "QUEST_KINGDOM_HOSTING_MILITIAMAN_T4",
    QUEST_KINGDOM_HOSTING_MILITIAMAN_T5 = "QUEST_KINGDOM_HOSTING_MILITIAMAN_T5",
    QUEST_KINGDOM_HOSTING_SOLDIER_T1 = "QUEST_KINGDOM_HOSTING_SOLDIER_T1",
    QUEST_KINGDOM_HOSTING_SOLDIER_T2 = "QUEST_KINGDOM_HOSTING_SOLDIER_T2",
    QUEST_KINGDOM_HOSTING_SOLDIER_T3 = "QUEST_KINGDOM_HOSTING_SOLDIER_T3",
    QUEST_KINGDOM_HOSTING_SOLDIER_T4 = "QUEST_KINGDOM_HOSTING_SOLDIER_T4",
    QUEST_KINGDOM_HOSTING_SOLDIER_T5 = "QUEST_KINGDOM_HOSTING_SOLDIER_T5",
    QUEST_KINGDOM_KING_HOSTING = "QUEST_KINGDOM_KING_HOSTING",
    QUEST_KINGDOM_KING_HOSTING_EVENT_1_A = "QUEST_KINGDOM_KING_HOSTING_EVENT_1_A",
    QUEST_KINGDOM_KING_HOSTING_EVENT_1_B = "QUEST_KINGDOM_KING_HOSTING_EVENT_1_B",
    QUEST_KINGDOM_KING_HOSTING_EVENT_1_C = "QUEST_KINGDOM_KING_HOSTING_EVENT_1_C",
}