---@meta

---
---RULER_TITLE
---Lua enum for ruler title assets used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/ruler_title)
---
---@enum RULER_TITLE_ASSET
RULER_TITLE = {
    RULER_TITLE_ABBESS = "RULER_TITLE_ABBESS",
    RULER_TITLE_ABBOT = "RULER_TITLE_ABBOT",
    RULER_TITLE_BROTHER = "RULER_TITLE_BROTHER",
    RULER_TITLE_BURGOMASTER = "RULER_TITLE_BURGOMASTER",
    RULER_TITLE_BURGOMISTRESS = "RULER_TITLE_BURGOMISTRESS",
    RULER_TITLE_CAPTAIN = "RULER_TITLE_CAPTAIN",
    RULER_TITLE_CASTELLAN = "RULER_TITLE_CASTELLAN",
    RULER_TITLE_COMMANDER = "RULER_TITLE_COMMANDER",
    RULER_TITLE_ELDER = "RULER_TITLE_ELDER",
    RULER_TITLE_LADY = "RULER_TITLE_LADY",
    RULER_TITLE_LORD = "RULER_TITLE_LORD",
    RULER_TITLE_MAYOR = "RULER_TITLE_MAYOR",
    RULER_TITLE_MAYORESS = "RULER_TITLE_MAYORESS",
    RULER_TITLE_PIONEER = "RULER_TITLE_PIONEER",
    RULER_TITLE_PRIOR = "RULER_TITLE_PRIOR",
    RULER_TITLE_PRIORESS = "RULER_TITLE_PRIORESS",
    RULER_TITLE_SISTER = "RULER_TITLE_SISTER",
}