---@meta

---
---Lua enum for taxation function asset types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/taxation_function)
---
---@enum TAXATION_FUNCTION_ASSET
TAXATION_FUNCTION = {
    TAXATION_FUNCTION_CHURCH = "TAXATION_FUNCTION_CHURCH",
    TAXATION_FUNCTION_HOUSING = "TAXATION_FUNCTION_HOUSING",
    TAXATION_FUNCTION_MARKET = "TAXATION_FUNCTION_MARKET",
    TAXATION_FUNCTION_TAVERN = "TAXATION_FUNCTION_TAVERN",
    TAXATION_FUNCTION_PRODUCTION_FLOUR = "TAXATION_FUNCTION_PRODUCTION_FLOUR",
    TAXATION_FUNCTION_PRODUCTION_MINING = "TAXATION_FUNCTION_PRODUCTION_MINING",
    TAXATION_FUNCTION_PRODUCTION_SMITHING = "TAXATION_FUNCTION_PRODUCTION_SMITHING",
}