---@meta

---
---Unlockable assets enumeration.
---Lua enum for unlockable asset/resource types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/unlockable)
---
---@enum UNLOCKABLE_ASSET
UNLOCKABLE = {
    UNLOCKABLE_CLERGY_CHURCH_RUSTIC_SPLENDOR = "UNLOCKABLE_CLERGY_CHURCH_RUSTIC_SPLENDOR",
    UNLOCKABLE_CLERGY_DECORATIVE_SET_1 = "UNLOCKABLE_CLERGY_DECORATIVE_SET_1",
    UNLOCKABLE_CLERGY_DECORATIVE_SET_2 = "UNLOCKABLE_CLERGY_DECORATIVE_SET_2",
    UNLOCKABLE_CLERGY_MONASTERY_ABBATIAL = "UNLOCKABLE_CLERGY_MONASTERY_ABBATIAL",
    UNLOCKABLE_CLERGY_MONASTERY_EMISSARY = "UNLOCKABLE_CLERGY_MONASTERY_EMISSARY",
    UNLOCKABLE_CLERGY_MONASTERY_TREASURY = "UNLOCKABLE_CLERGY_MONASTERY_TREASURY",
    UNLOCKABLE_COMMON_BEER_PRODUCTION = "UNLOCKABLE_COMMON_BEER_PRODUCTION",
    UNLOCKABLE_COMMON_BRIDGE_3 = "UNLOCKABLE_COMMON_BRIDGE_3",
    UNLOCKABLE_COMMON_CANDLES_PRODUCTION = "UNLOCKABLE_COMMON_CANDLES_PRODUCTION",
    UNLOCKABLE_COMMON_CHEESE_PRODUCTION = "UNLOCKABLE_COMMON_CHEESE_PRODUCTION",
    UNLOCKABLE_COMMON_CLOTHING_PRODUCTION = "UNLOCKABLE_COMMON_CLOTHING_PRODUCTION",
    UNLOCKABLE_COMMON_COOPERAGE_PRODUCTION = "UNLOCKABLE_COMMON_COOPERAGE_PRODUCTION",
    UNLOCKABLE_COMMON_DECORATIVE_SET_1 = "UNLOCKABLE_COMMON_DECORATIVE_SET_1",
    UNLOCKABLE_COMMON_DECORATIVE_SET_2 = "UNLOCKABLE_COMMON_DECORATIVE_SET_2",
    UNLOCKABLE_COMMON_DECORATIVE_SET_3 = "UNLOCKABLE_COMMON_DECORATIVE_SET_3",
    UNLOCKABLE_COMMON_DECORATIVE_SET_4 = "UNLOCKABLE_COMMON_DECORATIVE_SET_4",
    UNLOCKABLE_COMMON_FARMING_PRODUCTION = "UNLOCKABLE_COMMON_FARMING_PRODUCTION",
    UNLOCKABLE_COMMON_JEWELERY_PRODUCTION = "UNLOCKABLE_COMMON_JEWELERY_PRODUCTION",
    UNLOCKABLE_COMMON_MARKET_GOODS = "UNLOCKABLE_COMMON_MARKET_GOODS",
    UNLOCKABLE_COMMON_MARKET_LUXURY = "UNLOCKABLE_COMMON_MARKET_LUXURY",
    UNLOCKABLE_COMMON_STONEMASON_PRODUCTION = "UNLOCKABLE_COMMON_STONEMASON_PRODUCTION",
    UNLOCKABLE_COMMON_TOOLING_PRODUCTION = "UNLOCKABLE_COMMON_TOOLING_PRODUCTION",
    UNLOCKABLE_KINGDOM_CASTLE_ARCHITECTURE_1 = "UNLOCKABLE_KINGDOM_CASTLE_ARCHITECTURE_1",
    UNLOCKABLE_KINGDOM_CASTLE_COURTIER = "UNLOCKABLE_KINGDOM_CASTLE_COURTIER",
    UNLOCKABLE_KINGDOM_CASTLE_ENCAMPMENT_HQ = "UNLOCKABLE_KINGDOM_CASTLE_ENCAMPMENT_HQ",
    UNLOCKABLE_KINGDOM_CASTLE_MODEST = "UNLOCKABLE_KINGDOM_CASTLE_MODEST",
    UNLOCKABLE_KINGDOM_CASTLE_SPLENDOR_1 = "UNLOCKABLE_KINGDOM_CASTLE_SPLENDOR_1",
    UNLOCKABLE_KINGDOM_CASTLE_SPLENDOR_2 = "UNLOCKABLE_KINGDOM_CASTLE_SPLENDOR_2",
    UNLOCKABLE_KINGDOM_CASTLE_TREASURY = "UNLOCKABLE_KINGDOM_CASTLE_TREASURY",
    UNLOCKABLE_KINGDOM_COURT_HEROES = "UNLOCKABLE_KINGDOM_COURT_HEROES",
    UNLOCKABLE_KINGDOM_FORTIFICATION_1 = "UNLOCKABLE_KINGDOM_FORTIFICATION_1",
    UNLOCKABLE_KINGDOM_FORTIFICATION_2 = "UNLOCKABLE_KINGDOM_FORTIFICATION_2",
    UNLOCKABLE_KINGDOM_MESS_HALL = "UNLOCKABLE_KINGDOM_MESS_HALL",
    UNLOCKABLE_LABOUR_PAVED_ROAD = "UNLOCKABLE_LABOUR_PAVED_ROAD",
    UNLOCKABLE_LABOUR_TAXATION_DRINKING = "UNLOCKABLE_LABOUR_TAXATION_DRINKING",
    UNLOCKABLE_LABOUR_TAXATION_FLOUR = "UNLOCKABLE_LABOUR_TAXATION_FLOUR",
    UNLOCKABLE_LABOUR_TAXATION_MINING = "UNLOCKABLE_LABOUR_TAXATION_MINING",
    UNLOCKABLE_LABOUR_TAXATION_SMITHING = "UNLOCKABLE_LABOUR_TAXATION_SMITHING",
}