---@meta

---
---UPGRADE_TRADE_ROUTE_MANDATE_TYPE
---Lua enum for upgrade trade route mandate types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/upgrade_trade_route_mandate_type)
---
---@enum UPGRADE_TRADE_ROUTE_MANDATE_TYPE_ASSET
UPGRADE_TRADE_ROUTE_MANDATE_TYPE = {
    MANDATE_UPGRADE_TRADE_ROUTE_CASTLE_HARBOUR = "MANDATE_UPGRADE_TRADE_ROUTE_CASTLE_HARBOUR",
    MANDATE_UPGRADE_TRADE_ROUTE_DAVENPORT = "MANDATE_UPGRADE_TRADE_ROUTE_DAVENPORT",
    MANDATE_UPGRADE_TRADE_ROUTE_KINSTONE = "MANDATE_UPGRADE_TRADE_ROUTE_KINSTONE",
    MANDATE_UPGRADE_TRADE_ROUTE_MYDDLE = "MANDATE_UPGRADE_TRADE_ROUTE_MYDDLE",
    MANDATE_UPGRADE_TRADE_ROUTE_NORTHBURY = "MANDATE_UPGRADE_TRADE_ROUTE_NORTHBURY",
    MANDATE_UPGRADE_TRADE_ROUTE_TROTBURY = "MANDATE_UPGRADE_TRADE_ROUTE_TROTBURY",
}