---@meta

---
---VILLAGER_STATUS enumeration containing various villager status identifiers.
---Lua enum for villager status types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/villager_status)
---
---@enum VILLAGER_STATUS_ASSET
VILLAGER_STATUS = {
    STATUS_COMBATANT_KNIGHT = "STATUS_COMBATANT_KNIGHT",
    STATUS_COMBATANT_MILITIAMAN = "STATUS_COMBATANT_MILITIAMAN",
    STATUS_COMBATANT_SOLDIER = "STATUS_COMBATANT_SOLDIER",
    STATUS_GUEST_ABBESS = "STATUS_GUEST_ABBESS",
    STATUS_GUEST_ABBESS_ENVOY = "STATUS_GUEST_ABBESS_ENVOY",
    STATUS_GUEST_ELDER = "STATUS_GUEST_ELDER",
    STATUS_GUEST_KING = "STATUS_GUEST_KING",
    STATUS_GUEST_KING_RETINUE = "STATUS_GUEST_KING_RETINUE",
    STATUS_GUEST_KNIGHT_ROYAL_COMPANY = "STATUS_GUEST_KNIGHT_ROYAL_COMPANY",
    STATUS_GUEST_MILITIAMAN_ROYAL_COMPANY = "STATUS_GUEST_MILITIAMAN_ROYAL_COMPANY",
    STATUS_GUEST_MONK = "STATUS_GUEST_MONK",
    STATUS_GUEST_MYDDLE_PEOPLE = "STATUS_GUEST_MYDDLE_PEOPLE",
    STATUS_GUEST_NORTHBURY_MERCHANT = "STATUS_GUEST_NORTHBURY_MERCHANT",
    STATUS_GUEST_NUN = "STATUS_GUEST_NUN",
    STATUS_GUEST_PILGRIM_HIGH = "STATUS_GUEST_PILGRIM_HIGH",
    STATUS_GUEST_PILGRIM_LOW = "STATUS_GUEST_PILGRIM_LOW",
    STATUS_GUEST_PILGRIM_SOLDIER = "STATUS_GUEST_PILGRIM_SOLDIER",
    STATUS_GUEST_PRIOR = "STATUS_GUEST_PRIOR",
    STATUS_GUEST_SENESCHAL = "STATUS_GUEST_SENESCHAL",
    STATUS_GUEST_SOLDIER = "STATUS_GUEST_SOLDIER",
    STATUS_GUEST_SOLDIER_ROYAL_COMPANY = "STATUS_GUEST_SOLDIER_ROYAL_COMPANY",
    STATUS_GUEST_STEWARD = "STATUS_GUEST_STEWARD",
    STATUS_GUEST_TRAVELER = "STATUS_GUEST_TRAVELER",
    STATUS_GUEST_VILLAGER_HIGH = "STATUS_GUEST_VILLAGER_HIGH",
    STATUS_GUEST_VILLAGER_LOW = "STATUS_GUEST_VILLAGER_LOW",
    STATUS_GUEST_VILLAGER_MIDDLE = "STATUS_GUEST_VILLAGER_MIDDLE",
    STATUS_GUEST_WANDERING_MONK = "STATUS_GUEST_WANDERING_MONK",
    STATUS_MONASTIC_BROTHER = "STATUS_MONASTIC_BROTHER",
    STATUS_MONASTIC_NOVICE = "STATUS_MONASTIC_NOVICE",
    STATUS_MONASTIC_PRIOR = "STATUS_MONASTIC_PRIOR",
    STATUS_VILLAGER_CITIZEN = "STATUS_VILLAGER_CITIZEN",
    STATUS_VILLAGER_COMMONER = "STATUS_VILLAGER_COMMONER",
    STATUS_VILLAGER_NEWCOMER = "STATUS_VILLAGER_NEWCOMER",
    STATUS_VILLAGER_SERF = "STATUS_VILLAGER_SERF",
}