---@meta

---
---VILLAGE_TITLE asset enum.
---Lua enum for village title asset types used in the project.
---[Reference](https://www.polymorph.games/foundation/modding/assets/village_title)
---
---@enum VILLAGE_TITLE_ASSET
VILLAGE_TITLE = {
    VILLAGE_TITLE_CONDITION_ABBEY = "VILLAGE_TITLE_CONDITION_ABBEY",
    VILLAGE_TITLE_CONDITION_BURG = "VILLAGE_TITLE_CONDITION_BURG",
    VILLAGE_TITLE_CONDITION_CASTLE = "VILLAGE_TITLE_CONDITION_CASTLE",
    VILLAGE_TITLE_CONDITION_CITY = "VILLAGE_TITLE_CONDITION_CITY",
    VILLAGE_TITLE_CONDITION_COVENT = "VILLAGE_TITLE_CONDITION_COVENT",
    VILLAGE_TITLE_CONDITION_FORT = "VILLAGE_TITLE_CONDITION_FORT",
    VILLAGE_TITLE_CONDITION_HERMITAGE = "VILLAGE_TITLE_CONDITION_HERMITAGE",
    VILLAGE_TITLE_CONDITION_HOLD = "VILLAGE_TITLE_CONDITION_HOLD",
    VILLAGE_TITLE_CONDITION_PRIORY = "VILLAGE_TITLE_CONDITION_PRIORY",
    VILLAGE_TITLE_CONDITION_STRONGHOLD = "VILLAGE_TITLE_CONDITION_STRONGHOLD",
    VILLAGE_TITLE_CONDITION_TOWN = "VILLAGE_TITLE_CONDITION_TOWN",
    VILLAGE_TITLE_CONDITION_VILLAGE = "VILLAGE_TITLE_CONDITION_VILLAGE",
    VILLAGE_TITLE_HAMLET = "VILLAGE_TITLE_HAMLET",
}